// GENERATED by scripts/process-case-study-photos.ts — do not edit by hand,
// EXCEPT the `caption` fields, which are the client's own words from the
// source documents and may be improved by a human.
//
// These are real job photographs supplied by the client with the case-study
// write-ups. Unlike content/media-manifest.ts, these sets are ORDERED and
// belong to one job each — the client grouped them before/during/after and
// captioned them individually, so the order here is meaningful and must not be
// sorted or shuffled by anything that renders them.

export type CaseStudyPhoto = {
  slug: string
  src: string
  widths: number[]
  width: number
  height: number
  blurDataURL: string
  caption: string
}

export const caseStudyPhotos: Record<string, CaseStudyPhoto[]> = {
  "eagle-sliding-gate-repair-mesquite-tx": [
    {
      "slug": "eagle-sliding-gate-repair-mesquite-tx-01",
      "src": "/images/case-studies/eagle-sliding-gate-repair-mesquite-tx/eagle-sliding-gate-repair-mesquite-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAwAA4BaJQBYdiB4u7OwAADzt7vWk72J/wHwr6909RtcFT0KJhOVaaL7D2X984KNaL21JWfIUNbMJGX7QdFZGgLjsA0Bem/VKUjogAA=",
      "caption": ""
    },
    {
      "slug": "eagle-sliding-gate-repair-mesquite-tx-02",
      "src": "/images/case-studies/eagle-sliding-gate-repair-mesquite-tx/eagle-sliding-gate-repair-mesquite-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAgCdASoQAAwAA4BaJYgCdFKAAci5byR8k4AA/mFtpsck5cie8U2J+xGFgRJd2zGI+t3t5bYfEzDGYIpM4+njfLslAn5YUam/IoMyv/1MlwAA",
      "caption": ""
    },
    {
      "slug": "eagle-sliding-gate-repair-mesquite-tx-03",
      "src": "/images/case-studies/eagle-sliding-gate-repair-mesquite-tx/eagle-sliding-gate-repair-mesquite-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAwAA4BaJZACdAELT461mADh/bhi2Ow5qIsXUN+OuLN5I8hkMIkP8aBBIe2d/nh3b7L5XCpc+R4kenRP0l0lDaBtPDsTOdv/kmSKoQAAAA==",
      "caption": ""
    }
  ],
  "gary-liftmaster-csl24ul-gate-opener-frisco-tx": [
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-01",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBadA1pXW8v/YTwhjqwA/tyymrVT8Yx7A6X+n7O4TxyJJMRU1I7K2VMbQH3FLSYU0ww5vgPUL9ZPRudLFInt9/zTkCOaF/awZ3vZR/zbYq7K8mqP/0Czv6UHW/zQYHo/0aZCd5w6zh4y7YXcbZhc2wZjsQnkYYXoOAAA",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-02",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBUegmT2SgHfcVqwAP68gQVQ7oVxpXvxDJhSqNOiPXwV7KEgS6Hc7c3Q2dMqtJe9Km+pnkukNG3b6c+ezEUUI3fobWuTxAY50qkzltPpwatMjJ2w/DeTuMU1V3OVYPi8qY8edPrcTEJxs0kr7hmoLKIpmSrUJHwbHZ4A",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-03",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-03",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAsJas/aVxsQAAP5+mqb4PGk+2kGtWt3AlE+CBm0xoYM81c1PwBuaQ6dRSWjwPtKSvr86vsKMK0RvJ8FvM4XHBvHqzDKuDDWlSeWWzJVy39XCpe7a1p2HxVx6rC7YS8rSH3fzK01Pei/yuBBZ+JGi6/Dxny0+puN3TymPQIB5THscAA==",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-04",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-04",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgAsDWFh2TXAqBQAD+yKcw2NhbZ/1zUTysoTx2D/dpy1m/msALblN3/NO6xPBkeDRsl6kempDtrUOQQOCqexB0775UE17uGWsVeuEnb/K9q6vfihpx7c9nWbqgPXmre4bw8BooKLUx5QnXWcdT0AA=",
      "caption": "The photos below show the completed LiftMaster CSL24UL installation and the finished sliding-gate system."
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-05",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-05",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoQABUAPu1kqU2ppaOiMAgBMB2JZQC2yBjFTep+CphRiAD2qpWdmy/thY3HghkVAA+48FGOF/49bDyrYMQlKEt9UcU0xVJAbsrorDZsBI9du2+9s8aunqWH0XyuIfhb+1H1ts1HN36sX8Y1tl4AAA==",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-06",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAwAA4BaJYwCdAEQyrrG+Ny4AADN8lpMWJsCkVkjKXVH+uCoSy0PxlMg6uPMeBHZU2XEnZfakeVWk6xl7kTSGwK7kDjQudBkKN54ZhpBgAAA",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-07",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-07",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCxJUAAlf4BPBwpgo8ugAD+ZmGbqR993w4hWAzxSIfE2aWqaffaOCRp7OpOc6V02UHtcCbx3JU/MOAOj63tROQBZTebG/fXsMTu16BNx+0yeBp+5MtOhvZN8lbhzY6rZmgA",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-08",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-08",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJZQC7AD0M8a4+AD33qDC8altLSNEwYenRSm/WNsL1Xpfn8B0t4GZpa6X1JIp6nfhEhlN/h5Z8dra5+nzdkVg8AA=",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-09",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-09",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBUegzKarYVBbBEAAMk0kskx7S8IJGFy4Z40/MCgWvhG5q2t8nT924p/V2IbL3wEJkC8OWA7NcDQA4DBppmEmhnj+h+rfGFapaVPvOqD8k0iKJ7Yj3+5t81Omnzduz88sPK4jwkxPi1S/zE2wAAA",
      "caption": ""
    },
    {
      "slug": "gary-liftmaster-csl24ul-gate-opener-frisco-tx-10",
      "src": "/images/case-studies/gary-liftmaster-csl24ul-gate-opener-frisco-tx/gary-liftmaster-csl24ul-gate-opener-frisco-tx-10",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAgCdASoQAAwAA4BaJZQCsAYvX2uHrf7q/EcgAAD+0PxrFvSmCOvmB+0WGt1xSGODrazJPGN1p1WQuRnOC1Zr0Rmxwpgc2tEln1j86qEO8CG9qRW+NFF1cAA=",
      "caption": ""
    }
  ],
  "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx": [
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-01",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABUAPu1iqU2ppaQiMAgBMB2JZACdOUAAhl9O3rjMfAzrm9AAy/v5euhRxsbgptjJSEZUYulwghZ8jz3NgYfv94hS+087mu+jvH4HMjTLnE6OeeAgYpzUrt6Yf/dVybcnOmWiMKgj7/7btLZ20AAA",
      "caption": ""
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-02",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoQABUAPu1iqU2ppaQiMAgBMB2JQBOmUGMABgmThSjtIGMhmlgA/nWFyzEcxDbZEM2CKEiR2P7NVyDkUOyBJQypwocjZ7gy+gtQozfOAlF77d04WMV/drr07f9nAz0ALrHoGX0YrJmW6yxRdYv7uG5fbU7QMmm5T04FAKZ4wnIeyQS82qAAAA==",
      "caption": ""
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-03",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJYwCdACqK9e9qAAA/cPFkkQmEmduKJJQU319Rv/ksxuIoGRc9d5t3B2nE+JOyOysK/LC0eAWT0jL3v1ZmbUZb8Vh8R0KMewOQAAA",
      "caption": "New LiftMaster CSL24UL delivered for installation."
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-04",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJZQC7ADh5909oFAA+/adDkVsG+FzlrHWIce5o391kfZjZH5YJBm999zRJeJDbNNJaAHN7MIyBdpZq4D8M7PfREZCf9KNAHIWa1oAAAA=",
      "caption": "LiftMaster operator and work area during installation."
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-05",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwAA4BaJYwC7AYu5Zoi5eAAAP6D3LrOFmzu4NBIynCE8adiz+lRP96YpSaevndZ6EHVYdfB9SqwV1ApaPG3R8IHFuXFHNe290AA",
      "caption": "Installed CSL24UL beside the sliding gate."
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-06",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-06",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC/OBtkZxy6DwnoAP5En/cya9/4l7fEsrjtEP1k+7rS83+8jNFCaHufZCRoesQC94EQTIG2jrrXB7VeuluAmtKcuRJp0kUWE4zKFlSfMbidZEoAAA==",
      "caption": "Closer view of the installed LiftMaster operator."
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-07",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-07",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJYwCdACqGJSd0ADz+er1suhmm+XvMJXKKHvHO4ZW2rKzZ2MgW3JSjBlxB03zNjdIZdhMAAA=",
      "caption": "Wide view of the wooden sliding gate and installed CSL24UL."
    },
    {
      "slug": "liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-08",
      "src": "/images/case-studies/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx/liftmaster-csl24ul-sliding-gate-opener-installation-dallas-tx-08",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQC7ABuHlgrzsratojXeyIAAzZYogcF+nDSdE6fekLhye0nUC1yEzCRHMpas1Ir9jkBTCqI0inNGUCrePYjf7kfykoTPrN+w6WKG35yBXGTLfmckh1UAAAA=",
      "caption": "Additional view of the completed operator installation."
    }
  ],
  "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx": [
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-01",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA4BaJZQAAsSIPoDImBuAAP6CHPzRgx5mugRmKzjkl//+lemuay3iO0ig/4x7cT0AIXEPfLtdPodxFejwzzhQe+ZuLL4YtcYIAAA=",
      "caption": "Double swing gate and installation work area."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-02",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwAA4BaJZQAD5GtZwrJcrQAAP6sCzGNxNAV8RbbcVMhRIngnP3iZmpjqf68HJafSNBYFUjDcRvC6SHdprr+dVmUAUOZYTYQd6F7etpAAA==",
      "caption": "Additional view of the gate opening during installation."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-03",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJZQAAqpOjD4PsAAA4gT3quavfCQT4BWAEYHzmio+J1ifLrF+hFeQdD/cJ8tFM51vnNInX46r4A8FHIxgRzgQ3ztijYby0RwAAA==",
      "caption": "LiftMaster operator arm and installation components."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-04",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJZwAAttVcjN1UAAA+pvdPE+L1b3EykRoDrc3or1q/Tk1/lHpncZUTLf8LlC3nyf/7O8Pnj+aU1tMTCiWONoHwrxD/5ftNJAAAA==",
      "caption": "Operator arm and open control enclosure during the work."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-05",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAwAA4BaJYwAAuhGmD8+2AAA/oOb5n1MYqrm01XIHUhHOksDGrPkzqLwiTMaHPahCoPOx1MgZ6OPP9Q84h39WX33doMsiHfW+gAA",
      "caption": "Double swing gate shown closed with the control enclosure secured."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-06",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwAA4BaJZQAAqHh4W3gAAD+uoJXuJTqCAzMPWyOKRFJAFMM3beTldthJ32sT0tXWhI7hNJIaghfQGLOCTU6BEoXTk9dcVmPJPgA",
      "caption": "Wider view of the completed gate installation."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-07",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-07",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJZQAD48NaoNW1+MAAPyLhhUA3RWO4EvDCqfvNyCTIhDsCI3OaqP6xTgqWruVU0fsGBDqCi8fzpoPZSZDWfj02OeMAAAA",
      "caption": "Side view of the gate opening and control enclosure."
    },
    {
      "slug": "liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-08",
      "src": "/images/case-studies/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx/liftmaster-la400-double-swing-gate-installation-lake-kiowa-tx-08",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJZQAAn1fOiiIAAD+vlU5XC/ZELwbCoUh4oioHx56AAe0AfmMUUkokCGcloJnWq3KJI9CfEpTco/HLcENAAAA",
      "caption": "Double swing gate shown in the open position."
    }
  ],
  "liftmaster-la400-swing-gate-repair-university-park-tx": [
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-01",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAwAA4BaJZwAAVDt/2xAAP7x4OG3T8t3FDZ5LJ4aD3N0ZdqXKR5g/BtNvOp/bfHNqi7DLGz78sTTsHIyqBcOKWdS1pluIq15YoAA",
      "caption": "Gate and control enclosure during the repair, with an operator arm removed."
    },
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-02",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAQCdASoQAAwAA4BaJZwAAaqkAAD+5jptaWf9kMvNTBWLzZ+9hmxXZ/+P106IZesxHQklYUK1MD8KdzEpWvgW/gbPIY1FlBB6UFAA",
      "caption": "Close view of the operator arm and mounting area during the work."
    },
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-03",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAwAA4BaJQBdgBb2zxR8gAD+mxkQ6bV80hPDOemCH/3HsYxqNhswbMoSjx6lHuPPnhqb2YnL/F8flySXoqMYjayw/UOjBJ01j0nr8ENDJrbqsnuHKRgAAAA=",
      "caption": "Replacement LiftMaster arm mounted on the swing gate."
    },
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-04",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJZwAAqH5QmiVUwAA/DgidWqN8DJBHYeyo9hY0qJuSSKiUZkOrcTuvw6NJ442p3Psqz5jD4vEX2hAAAA=",
      "caption": "View of the swing gate and work area during the repair."
    },
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-05",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQAApMY24ua4AD9xEUZAx8H3rxHjnP7iZ87pSbPK2caktiTZknimyrteh/n2VdeTrBHd4xet32wgQAAAA==",
      "caption": "Additional view of the gate during the repair."
    },
    {
      "slug": "liftmaster-la400-swing-gate-repair-university-park-tx-06",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-repair-university-park-tx/liftmaster-la400-swing-gate-repair-university-park-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAwAA4BaJZQC7H8AFBliOUb+DAAA/m0QTYxDAyhU6KXrl1iwCWTIbLe2GLMtYa5aiq4DA7DyUnwYsSoVNnqydTW8QPCOFG/moNyTcHqEIlAA",
      "caption": "Completed installation with the control enclosure closed."
    }
  ],
  "liftmaster-sliding-gate-chain-repair-dallas-tx": [
    {
      "slug": "liftmaster-sliding-gate-chain-repair-dallas-tx-01",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-repair-dallas-tx/liftmaster-sliding-gate-chain-repair-dallas-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJZQCdADdSCu7uCkAAPl4vgY3KnP20jCLTa5kzT5EsVWeQcDVzx2YrmwLtDlrMDTtQcjWn7BHv4lxquza+CzxYL5LWCqMeDv6QAAA",
      "caption": ""
    },
    {
      "slug": "liftmaster-sliding-gate-chain-repair-dallas-tx-02",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-repair-dallas-tx/liftmaster-sliding-gate-chain-repair-dallas-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JZQC2yBYpOGlAoSdfmcAA8MvyH39oM8hfckMzN0/dXalBmlzb0SCrGwG9MC/2RAAkSnUu7rUufddKLRWJtJIVyMLNuELlslrHEgTJpfH/uPfDEbg2BR0+0AGRxEAA",
      "caption": "The completed repair photo shows the LiftMaster sliding gate after installation and adjustment of the new rust-free chain."
    },
    {
      "slug": "liftmaster-sliding-gate-chain-repair-dallas-tx-03",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-repair-dallas-tx/liftmaster-sliding-gate-chain-repair-dallas-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAwAA4BaJQBOgBtlf+ZW8AD+ZXo+1u3ndEr9+EeMFK3FXcW+l9XFmqN1hlf+KuJYeZLhkTk7Zsr6Izr/P73x0YAAAA==",
      "caption": ""
    }
  ],
  "liftmaster-sliding-gate-chain-replacement-dallas-tx": [
    {
      "slug": "liftmaster-sliding-gate-chain-replacement-dallas-tx-01",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-replacement-dallas-tx/liftmaster-sliding-gate-chain-replacement-dallas-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQAAwAA4BaJYgCdABqb/CoAPDbBE+OzXmECP+9c0elOpg1SKSacrlWpyo69gypGmW8uArqRxal/jHqLdnlMpgAAAA=",
      "caption": "LiftMaster sliding gate operator with the enclosure open during the chain replacement."
    },
    {
      "slug": "liftmaster-sliding-gate-chain-replacement-dallas-tx-02",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-replacement-dallas-tx/liftmaster-sliding-gate-chain-replacement-dallas-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoQAAkAA4BaJQBOgBc7pqgAAMm6UG0t7EHr4p0Uisg3p1QVYilJvD9hrfnS4he38eGGRYmKAAA=",
      "caption": "Sliding gate and chain along the wooden gate during the repair."
    },
    {
      "slug": "liftmaster-sliding-gate-chain-replacement-dallas-tx-03",
      "src": "/images/case-studies/liftmaster-sliding-gate-chain-replacement-dallas-tx/liftmaster-sliding-gate-chain-replacement-dallas-tx-03",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoQABUAPu1iqk4ppaQiMAgBMB2JZACdABPNIaUMCtZfh9gAye4rYhQcfPiLSnpfNlB1N9bMpaeAOPwbSH2QS0o70JJqs7ciilNAKItK6CHor+23erLMmI4gAAA=",
      "caption": "LiftMaster operator and replacement chain installed on the sliding gate."
    }
  ],
  "liftmaster-sliding-gate-repair-richardson-tx": [
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-01",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJQBOgBZz/B4OgAAA+MOGiezKTCYLEnPTwcced9fWNMJE8kjoUh0FK4vSKcLnjdJdltD3drNMiuJzg9qkPdG0ka+DRylyqVNLAAAA",
      "caption": ""
    },
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-02",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgA4lctZHeTckwHpWAAPgtAtxqLXLg9R+ikygusP8+LHlsSBgwF19fMvaxS/8oyBh1U89EgD9Zvud+TmpOMSoFxK0JKEupPw7iwlDVzVPs5CLIeLuBzzSbN8KO8PtduRUy3xdz4o8TjePZ88B8yrEZPELNVz/ITlI/EjAAAA==",
      "caption": ""
    },
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-03",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAwAA4BaJYgCdAYvrjBW4I6gAP69S9c0Cs3wuJt15o8u7/DYhPJvXfN1MXXwiSVJ1AshOCJJdetB1R7DSc3s4Ph3ynirJbuRp+KcW9dNdoAA",
      "caption": "These photos show the LiftMaster sliding gate system after the circuit board and both 12V backup batteries were replaced, followed by programming, adjustment, and final testing."
    },
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-04",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgB4PoVwzAAD+prbHvErZ4qCIjkia19QI0yoCYePVlusLkyALgonEeuPmuSrDTZGPbwAAAA==",
      "caption": ""
    },
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-05",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAwAA4BaJYgCdADxyCYAAP6mc+cRicthd1RFp5ebeXdd1amGsBGmLoc6KXVK1V9NEWvlufhObJnYR1KvHDyDq8WoVgmMnaUW0dVhEAA=",
      "caption": ""
    },
    {
      "slug": "liftmaster-sliding-gate-repair-richardson-tx-06",
      "src": "/images/case-studies/liftmaster-sliding-gate-repair-richardson-tx/liftmaster-sliding-gate-repair-richardson-tx-06",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOkIJQVoaewNmKDR3wktdgA+2OqqT7n7q6tXpDAtnfp7sjJn7vhfSlcKW7skoS7V4kh4gRQm063lyyyeojXzJmvHV6qrHDKntZwsPdjJnRX+pjizz9GqXIWJUzvku2X5LWBt3m/Axvy6QAAAA==",
      "caption": ""
    }
  ],
  "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx": [
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-01",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBlABCk1RRZDCSf5tND0qYAA/uJV+ePYW/GcIddEdon7vb0ERDGFdYWK6zm+XL+ibcnVTj8Zlw7oGKDfiMliapG55n+8URZ6TsL9xTrKroqmFSqvxh5hMARYv9se8s7zcI2dXFV1Lz9x10xMn/9rzra9olWtrD1d7f+cAAA=",
      "caption": "Control enclosure and backup battery compartment during the repair."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-02",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQAwCdASoQABUAPu1iqk2ppaQiMAgBMB2JZgAAQNFXftZ2pz5AAP5nAEyNqc4VsPi8E+CTcEQ7zJlE7av6CRnNYG35eyEZKtHY9RPG7bSQZIFoZnnWwDOdCeYHLwacOdb8+F+Vtv8BIx3XSQKvn3o/mLTvR3gJa/OYaBI3jm+gLibAgAA=",
      "caption": "Close view of the backup batteries and wiring."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-03",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAwAA4BaJYwC7AYtzaeVC4AAAOApq844x2W69auD9X5kY3UY/cGuFL/crf8t42eD7P1Hyj7ufMb0YP/KF9aDt/MMSTkFRNpHPwPzoR480+tGRli581hY9AA=",
      "caption": "Operator arm, gate, and work area during the repair."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-04",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAwAA4BaJZwAD5JvNTaeqNOyAAD+6EnOGsBPXKr7A8vtguOVt1sf23+zQbPv3FeJHh/Xg6FEW82jkKJ3aOZfF/1LR2/bHaRgSlZ+NuyUw1aE7ohPFbSQFHoAAA==",
      "caption": "Solar panels and open control enclosure during the work."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-05",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAwAA4BaJQAAX0jLqNvH8wAA/lv+uitpcMnxRcjxEsTvag6cOnMyLCv3N/lKU/w1blIqJQ3sVqcntxS5ZObPykhZN9t5HcAqtRNoBv8wAA==",
      "caption": "View of the swing gate from inside the property."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-06",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAAwAA4BaJQBOgCIKXD6oAAD+tCW5ww4pdBJpPOtl/oxyhpwpQh0vtnzE09xBgFgVfHPtauF8it7Xd6FgSJJ61SP/MLz5t0gdMsj3qMZxRFntQTIUAA==",
      "caption": "Additional view of the driveway and gate opening."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-07",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-07",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAQCdASoQAAwAA4BaJZQC7ABVYwAA/tdx7i/dY95pqNKJoW0o2CpTQWpMWgXfW/+GwtnPZlrmrPVJ1xuEXyFQiFMMEOvvqyLXAAAA",
      "caption": "Gate and solar panel arrangement at the property."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-08",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-08",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZwDKACIfwPaX/5g0bVNSlWc8AP7UXEvQ8ZPK0ecmFqYToRWYsxovDlDTVUcCpx7mbcgiXPfFjTPxfQPOQ/VHWiCItbx//JlDF3bzAPc8d3c1HrSHyBIrK/vZwc4hE+Gm2/CzSYNXBpUQwnKJkAAA",
      "caption": "Two solar panels facing different directions, with the control enclosure closed."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-09",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-09",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAQCdASoQAAkAA4BaJZQAAaqYiAD+W/9n4nkZR0sklVf+W19ho/geic8Jby9Zfzzu6+QiGITxEpwPlzNuhPSiW2bj//7CbQn4EAAA",
      "caption": "Wide view of the repaired swing gate and solar setup."
    },
    {
      "slug": "liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-10",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx/liftmaster-swing-gate-repair-and-solar-upgrade-wills-point-tx-10",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwAA4BaJYwAAug4XMSpgAD+1/uy/1uX0sxsu78YAAqJNaN7bhNsKQS034bnvJzeeMMGJDzT6mPaazh63IrygUq+Y/eA7WctAAAA",
      "caption": "Additional view of the gate after the repair."
    }
  ],
  "liftmaster-swing-gate-repair-mildred-tx": [
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-01",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCw8rANwAN+yvBKTQwgAP7n4Cw8W2rVhT6ntOK4E0IcndlW+7mOBa2N8ZyUw3GQDQv6DEvhZQTkwu6wD4Tmc+b3g6tBOa7/aWqbjpIMhop0CA/xJnemEeuSX5MJPERG4KCpcuVhobhRQvR56BGAAAA=",
      "caption": ""
    },
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-02",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAQCdASoQAAwAA4BaJQBdgBEXjeMIAP64L5TbQFxYfkHYZRvfrt8NIdK1jcn8v7e1WrXu1Rxw/oNIIwedF2DtMbbKIa5CPh/ujPm0vZtC0fzaq9QACcAA",
      "caption": ""
    },
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-03",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJYwCdAEUoR6asQAA/gNLoiFd+HsvM8TQ0Q9EhKF97A1fXz9tMzHIH9pJF0ANB+kwuZAJq4cF7sRmdc0C1xQiS+f7tBTzikd/ULjbQAuUAA==",
      "caption": ""
    },
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-04",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAwAA4BaJZACdAEfvLUABoAA/rQRF8A1zPUcm1rP+6JCbKIauOLZMjvFJfg36AOWhy1GBWBmxxd223bOUhK6Jy/V2302Dz8ShP4otLxS6648AoLOSpTGkQAAAA==",
      "caption": ""
    },
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-05",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJYwCdAEMS2vtPwAA/rQkrBhQUSr6o80ppovyQ/bd5p+KSusjmTPCV377Gcug+h0IzsaA1WMYVBZuzbv3aQRuxNqFljp9QtVp+4AA",
      "caption": ""
    },
    {
      "slug": "liftmaster-swing-gate-repair-mildred-tx-06",
      "src": "/images/case-studies/liftmaster-swing-gate-repair-mildred-tx/liftmaster-swing-gate-repair-mildred-tx-06",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdkGxBId1BNxqPf3vAgAAD+ayxKZwdbxUpEF+1lzb/z53n1Bgzk9vWeEBz0UW40ZJurxaVUKfMHMy9gJLHgZ6HCQOLIQigiY0T4GtNCGtKJV98oTuoIBKtLvR1fZNhNDRfHEbVff3Fqr/dWh3N/gu2OGn3gKGkXrWDU9CADscyb90OKCwAA",
      "caption": ""
    }
  ],
  "ramset-sliding-gate-gearbox-repair-richardson-tx": [
    {
      "slug": "ramset-sliding-gate-gearbox-repair-richardson-tx-01",
      "src": "/images/case-studies/ramset-sliding-gate-gearbox-repair-richardson-tx/ramset-sliding-gate-gearbox-repair-richardson-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAkAA4BaJQBdgCKOODQgAAD6n+j8AiOOj/K6cuBDtuFC6xaaieD4oxxCZx0arJIPJyUwV0WCSo3kHg6lw3O0iqMoQAAA",
      "caption": "Ramset operated wooden sliding driveway gate in Richardson, Texas."
    },
    {
      "slug": "ramset-sliding-gate-gearbox-repair-richardson-tx-02",
      "src": "/images/case-studies/ramset-sliding-gate-gearbox-repair-richardson-tx/ramset-sliding-gate-gearbox-repair-richardson-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwAwCdASoQABUAPu1iqU2ppaQiMAgBMB2JYwCdABIw91x1YXG1MAD+eox4cZuMZud4/4Umad/g5MM12F9JAgyxi8nzISGMKobVUs7BID7u6+zn9LTzwPSIrvC6MQ/E3zlhvx1QHqO+3A2xC2SGPd/NysvW8TE2q/sGWagVOneEAAAA",
      "caption": ""
    },
    {
      "slug": "ramset-sliding-gate-gearbox-repair-richardson-tx-03",
      "src": "/images/case-studies/ramset-sliding-gate-gearbox-repair-richardson-tx/ramset-sliding-gate-gearbox-repair-richardson-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAwAA4BaJQBOgBhg4dv+udgA/tCSM2FE4aOtraRml5NArHBBjXI3Nlnk6ocUWjEisoP2qxniVNhFJOnx1hpgAAA=",
      "caption": "Left: Ramset operator with cover removed. Right: gate and operator during repair."
    },
    {
      "slug": "ramset-sliding-gate-gearbox-repair-richardson-tx-04",
      "src": "/images/case-studies/ramset-sliding-gate-gearbox-repair-richardson-tx/ramset-sliding-gate-gearbox-repair-richardson-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwAA4BaJQBfnCIHfhHjrMAAAPwB539NlwWSM8+wXwh5smaMFWe/rYbIyt7bZjBKhs1bzmViBYUljcLt98cEpOWEIUvtgAA=",
      "caption": "View of the sliding gate and driveway opening."
    }
  ],
  "swing-gate-circuit-board-repair-southlake-tx": [
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-01",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JbAC7ACBobVa3L6Kn1dMAAPx4V72bmDsyTWPJe0yIzL7DHD4ROgJfGhvL3XOhcZhYbcI9iCMA7U53q86mrXvUZAbAK1ODJjs5LSlrhthpPwCu+/+J3xDCSoICZMkN2G8FgDvKGYFGoRAA",
      "caption": "Original green circuit board with visible corrosion and contamination."
    },
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-02",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-02",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZQAAK7iJIYsQdMoAAM4IpK25yLuA2+IILDvygtKEgjpGKnFPYyylzqDxenGj7wiALELmnVZM/g7rXIylWw90QHYylQa0zFxbR4n3ZaqdLfupXb0heCDxttzOazTrBMORX9SjEEG4sxVqYhpkAAAA",
      "caption": "Backup battery compartment and debris inside the enclosure."
    },
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-03",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAwAA4BaJYwCdAC38VA+LADOPuLrQXEhhH99bEuaKcHZG/5JMgocZj9ENcDGy0+4LFlQcQsyIGNtKwHspmZPsmSGpgVZ74UhNjyqFYmIvZQbNgIdXV6qSZAAAA==",
      "caption": "Replacement circuit board installed in the control enclosure."
    },
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-04",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwAA4BaJZAC7AEfvwGMbAkAAP7vH4poyLfoTBYik2qKB/OxNBlzGuOkJTOpGhy7T1U/ArifZZo65G2GYN85VsAAAA==",
      "caption": "Swing gate at the Southlake property."
    },
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-05",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoQAAkAA4BaJZgCdABTpAAA/VPEXP9VZIoj00T+ZRj7nfjD1m/wa+vajPqhUSmPG3SDIG+vTY3FC8z1hyy9FGL5JaSuUasHAAA=",
      "caption": "View of the swing gate and driveway."
    },
    {
      "slug": "swing-gate-circuit-board-repair-southlake-tx-06",
      "src": "/images/case-studies/swing-gate-circuit-board-repair-southlake-tx/swing-gate-circuit-board-repair-southlake-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkAA4BaJQBWAB6t/7igAAD+5lJVF8nBP62IaEbHGIgQdPsvnuw6zqOz6ORgziB1mJl+EYomHOg+AAA=",
      "caption": "Additional view of the gate at the property."
    }
  ],
  "us-automatic-solar-swing-gate-repair-fort-worth-tx": [
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-01",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-01",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCdABtmxSsd/iRTiEAA/MqXvsq5AthtQdefrbP/VvBSitsabtWQbJN5WFQgRArCMxq/swkTXYQoFq2ispv/5jsb7ULz81o61+5nOsi2OXYq2iQzpV9nYx+3McQpc/pteQ29xy/RuyBoiqjKDtMZFmQQv9ISwAqGP19X38j4VOAA",
      "caption": "Corrosion on the existing control board."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-02",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwAA4BaJQBdgCIcp7M6+5ygAP6mwvAGjhBIGZHG+IiX2pEfibOddPQzsMwDCLqWxAdvseYSwK1fkzanMfqCIAHnlYXK8xLPgb0mJiOPsWe6gR7DVsQA",
      "caption": "Removed US Automatic Patriot control board before replacement."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-03",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJZQC7ADv9WsXklAA/HTGCrqkyLMi/pH59qJr5JbHOU4zTjqILyWouma3a84RGuQ5aL20sBWlRMPybB/MQAAA",
      "caption": "Replacement board installed; electrical testing in progress."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-04",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-04",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JZwDG9BmgOejVEcmSAADwDD17pgF7vSxozFcSTEP7njBgo6D4HK0vSk1xFXCTjNJ6/hjs4fJeh2mSebgkwb1DpXbHHBV3l5t8qkOzd6ce0erBVsWmohURCz8WosQK7tciYAAA",
      "caption": "Existing gate arm opened for repair rather than replaced."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-05",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwAA4BaJYwC7ADRrDQoghHAAP6+RSq/3OUfFJMTvNdcJwKd8Rt4JrYNOG1OtnDyEKGvd1cSspVVpJFq1InUT1hD3TBONI9iBsR2gAA=",
      "caption": "Gate and operator enclosure with tools visible."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-06",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkAA4BaJZQC7ADLuWUhmBAA+p0MX8LnZXxdScsQJ92WAd8epMLfb6+BhZPCudqn9K6inSxYyspFlSBQAA==",
      "caption": "Gate swung open during adjustment."
    },
    {
      "slug": "us-automatic-solar-swing-gate-repair-fort-worth-tx-07",
      "src": "/images/case-studies/us-automatic-solar-swing-gate-repair-fort-worth-tx/us-automatic-solar-swing-gate-repair-fort-worth-tx-07",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCo9B4hXavUq8Tl/RfjlAD8JnbZpkdcmMixdFI4FELuPfFAgXdGn83QlPGNUAaX2VAXug54JZPqORv7Iyj1yPDKMnkCKv7TDgfabVD5TdR+sXh7/o2vwQkQZ46tPRm4tCHcYq03gAAA",
      "caption": "Wide view of the gate and solar panel during the work."
    }
  ],
  "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx": [
    {
      "slug": "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-01",
      "src": "/images/case-studies/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwAA4BaJZQCw7D7d6yA9oAA3MbR4Z8aSyMdW+nrbKFSff9wP7etr/37Kkxkbtrcnsd6HRqbQeYDB4Tdk/nllC0ekMe+4eCV282voV1qI3c4OgAAAA==",
      "caption": "Battery replacement and work area at the US Automatic control enclosure."
    },
    {
      "slug": "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-02",
      "src": "/images/case-studies/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkAA4BaJZQCdADHmWJwXAAA/vDpaEksEGUPTx6FTe2J1kETRAEL3go955Lq3wcw9jaztZADtPYAAAA=",
      "caption": "Battery, control board, and wiring inside the open enclosure."
    },
    {
      "slug": "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-03",
      "src": "/images/case-studies/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkAA4BaJZwAAh6fo/uwAP712yjeowDbmvha/n9Mh08oyaI/exU/K6jPNX+w4Dk+AAAA",
      "caption": "Swing gate and operator arm at the Prosper property."
    },
    {
      "slug": "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-04",
      "src": "/images/case-studies/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAkAA4BaJZwAAudSLtKwAP7vSGcs6C24fnnDPL9A1wJfJxSCD6NZ+RLSPPgr928XAAAA",
      "caption": "Additional view of the swing gate in an open position."
    },
    {
      "slug": "us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-05",
      "src": "/images/case-studies/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx/us-automatic-swing-gate-arm-and-battery-repair-prosper-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoQAAkAA4BaJZwAAhzLIOAAAP75GGQDOVxyVb6xI/SoGHX7PLl1zX5HI5eF82d8+AA=",
      "caption": "Gate operator arm and control enclosure during the service visit."
    }
  ],
  "viking-gate-opener-refurbishment-richardson-tx": [
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-01",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-01",
      "widths": [
        400
      ],
      "width": 707,
      "height": 1140,
      "blurDataURL": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADQBACdASoQABoAPu1kqk4ppaQiMAgBMB2JQBOkBswZAfsSIV5llcmeavDeMu0MAAD4Ji8/DAWyYBiLFvtclxpq/IqLkF/j0GPttfFDHXdlfSJeyc+pkhHsiGFkDL0Fz8gA1HpwIR/hU9OvR2SU1GmEJ59bxpk5BMFPEtz2rftuQhehZPbn16hHzR4FOdSEAxfDaAfss+vmoqGpSIeoAB270aT7SwUg2C3RNznnX3LKj3gAAAA=",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-02",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-02",
      "widths": [
        400
      ],
      "width": 707,
      "height": 1422,
      "blurDataURL": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAADQBACdASoQACAAPu1qrU8ppiQiMAgBMB2JYwAOcFuCLsF8Z9zxC1nB4E1pepjbUAD+wSd2TFBCZqKF2fP3/Cq24R7nAAS/j/WsXRTduz1FwpDhZSP/O1Z2/Pm8ERb0O3BS/izl8Tt1f+nb9GKnCMbxeDyF8QmosMKq3t+VJVZ87pMP8wg0M0rl8qjJe482rf7zP2Gqerl/xEzBYswDYEWOFVX5bDNN0Yx0e0O5/deEF0OeaJ/HG6ejSC29rcRBAAA=",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-03",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwAA4BaJZwAD5CQTZ3WvgAA/tHj6LxRXuIM+34kv5MHt9xJ7P1yHh0UhkFdLq6vjp26UhFcTIR+CxlApEEvD2fjtaUQXh3y46nl4+stQgAA",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-04",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAwAA4BaJYwCdAEM/fNtXAAAzjpgI2tU0YTUGxJpIdNmQ468pD/s14hi3pF8kdR1GiUjndI4owYF/Xk8yvDsPsfGRCW6+ydDyWWbE1lbmACXcAA=",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-05",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-05",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCo9BQxmjuQACwwcADiakIdhgx4cMV2x3eWWkZ2IFCkXJnoJAmQvafDgJ7Nc3YCEMX7OPfTJ0DgcAqJaVoK13h+2xeLlTZ3UiYY6+b4SwgAWDxRcAnS9n6TYAAA",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-06",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAwAA4BaJYwC7AYt9WQf/L+qMAD+fctwkZuyHvu396UYBK/lUsdQqaNMc0dGMJwrmtSp3tYupg1+nI1WNIxsmX1SDMQKrg4ngPOke5IAAA==",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-07",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-07",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAwAA4BaJZQC7ADhWh4CDGAAAP4japnZhUUFIFSWCBmCPoUz1U8q5IJGWcRi4VveAorVm1uZZFDAlUM5TVv02BYzyQNU1nQLQpW0H+A4vm4OCAA=",
      "caption": ""
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-08",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-08",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACwAQCdASoQAAwAA4BaJQBdgBmxT5rAAP58Qy2mNxTCp0FMOPxArEqffJKW1WkPvCELv5ivH7BrlNc9IkzsYraY+rKyviKVzVF18qw4wwgL7gYGCxwQAA==",
      "caption": "Reassembled Viking operator with the protective cover ready for operation."
    },
    {
      "slug": "viking-gate-opener-refurbishment-richardson-tx-09",
      "src": "/images/case-studies/viking-gate-opener-refurbishment-richardson-tx/viking-gate-opener-refurbishment-richardson-tx-09",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJaACdADbfFyjssAAzH4iQ6BrG7rPufg3wGhCMzXJ31rgQlUR6bpZfx/AXRrATcWHjldq8jBmuqDUCyn4egAA",
      "caption": "Completed service: refurbished Viking sliding gate opener operating on the gate."
    }
  ],
  "coppell-tx-eagle-2000-sliding-gate-repair-case-study": [
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-01",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAwAA4BaJaACdAC9zKLTAAD+Wy0d0+dJ2/sKLxIuJ7kubLR8rsgiu/nZ4mO1ttrlfpehMWVA1gNZpOV5cm4yl/VwMb3Xv+V6Gqy74/V6xwAA",
      "caption": ""
    },
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-02",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAwAA4BaJZACdAD1dBXxYAD7dQsIbukm9dLF1NSXiffJezkekuoLvwoEG8N242xampyGnXc08GCR/7QGgfrmRAAAAA==",
      "caption": ""
    },
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-03",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-03",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JQBOgZYAwQdFcL3RPkHVMAP37+47VrHqMxAt69Gb7UpILRKNLulIQTJxRsPoCq56b1NTueJ4LwNCwCqspZpYokUHgibceRuboNTzr7NlwNfgPjiu4dt3IfZO09IvoNQrG4oqP3VXTF/SzpPJcu2RSUm1/3t5sHpuECySGDaz2M+WV5uIAAA==",
      "caption": ""
    },
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-04",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwAA4BaJZQC7AD0tXHkpmQA/O8U8pZVqKunpP+X4DO8jF98HxGM8HJVfZzb0SYhkEfsJ0xFMQAA",
      "caption": ""
    },
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-05",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAwAA4BaJYwCdAB3gYH9AAD5Xp7FS/jhum0E7ZrW6W3AN8Gx0AJvNY1SXCqAUwdVgW72vY2MZye+mEzzDy7jZx1yR83DDqeC4jIAAAA=",
      "caption": ""
    },
    {
      "slug": "coppell-tx-eagle-2000-sliding-gate-repair-case-study-06",
      "src": "/images/case-studies/coppell-tx-eagle-2000-sliding-gate-repair-case-study/coppell-tx-eagle-2000-sliding-gate-repair-case-study-06",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA4BaJZgCdAC9V6cgPgAAye5GJzLxVVJeCnV1EI4g2xHnB6uYgvhoZRuHPiktBNzK0HGFUR5z0+v+mjevrx21GFFfiAA=",
      "caption": ""
    }
  ],
  "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study": [
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-01",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAwAA4BaJYwCdADgy9I3AGQA/rIyTNSyb6jovuy4bRZWhycVJJITZezNfNWCwMusnST/GbrES0NNScrbqInpEQAAAA==",
      "caption": ""
    },
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-02",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJQBdgB6P3gFs5GAA9lUI6cgiuJHno2G5nHBuANCue5ThdQEGmYkcCVlYk2XjvwAijGX1TxByKeZARw2vW6FIWMMM+cZ0AAA=",
      "caption": ""
    },
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-03",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-03",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoQABUAPu1iqU2ppaOiMAgBMB2JZQCdAywBwA7gjR/pJOn//+G/AAD+3/zjIdQnOlyr618YWEuYLHAEztDgiCiT0ks4BWvxuWj8m5H85NBFIso0d5JDBiE/+1w93tQIpIa8ecKAWx/Ev9w8P3shdkDQdMgIil279x2DBExrypGClOBwGSzwAAAA",
      "caption": ""
    },
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-04",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-04",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJQBdgBko7lOgEAAA/tg9AYKroAgVc9vywtbe10ZTM5DOIpEvwNxIMsKS7BIeLZhfFl8GMe/+xW5wCo/GAAAA",
      "caption": ""
    },
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-05",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAwAA4BaJZQAAu0C0ueSLAD+WFcxO0NplptrX9ercifw+mE4uJoQMku3FRQ8CR0gG/GsAdHU8fs9eubNpT18SGAIdAKaXBgAAA==",
      "caption": ""
    },
    {
      "slug": "dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-06",
      "src": "/images/case-studies/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study/dallas-tx-liftmaster-csl24ul-sliding-gate-repair-case-study-06",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JYwC06Ba5fSIcJvKu8SYewAD+38Mw7Fys3KTeqvQVvfmwfohwA/LB/xsVetpaO8LJE5TfusHhQuvPTeIdnthqvBVKoKX73bdrr4xbVBkKxENO8+HzXVRJ7/L8JhZUBPWITHtDAAA=",
      "caption": ""
    }
  ],
  "liftmaster-la400-swing-gate-opener-installation-dallas-tx": [
    {
      "slug": "liftmaster-la400-swing-gate-opener-installation-dallas-tx-01",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-opener-installation-dallas-tx/liftmaster-la400-swing-gate-opener-installation-dallas-tx-01",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAwAA4BaJQBOgB6SYRDLaAAA/tx6jm93gZwP7sAo3psY+NfUrnAaXZwKdQPDE3YoD1SJXTXR9VXt+2meGdU555AwcCyHsAA=",
      "caption": "NEW LIFTMASTER LA400 INSTALLATION"
    },
    {
      "slug": "liftmaster-la400-swing-gate-opener-installation-dallas-tx-02",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-opener-installation-dallas-tx/liftmaster-la400-swing-gate-opener-installation-dallas-tx-02",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 864,
      "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAkAA4BaJYwC/OEXdj/xlZYAAP7CKjjohvW6mQQ6G1CKHs4MAj9C6w97aQUKv76etLmuTXDNm1324LFnnQsOtYe/LrCAAAA=",
      "caption": ""
    },
    {
      "slug": "liftmaster-la400-swing-gate-opener-installation-dallas-tx-03",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-opener-installation-dallas-tx/liftmaster-la400-swing-gate-opener-installation-dallas-tx-03",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAAwAA4BaJQBOgB+LhafLqVoYAAD+QOtHiUdiUDu0y9XneM3MmgtK3Y7JWHaeNuLOw0W3TICeBuMX8Lw1v3J9QSmSeLzNuIrdc/5o6WsLKPykAAA=",
      "caption": "• Removed the existing GTO swing gate opener"
    },
    {
      "slug": "liftmaster-la400-swing-gate-opener-installation-dallas-tx-04",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-opener-installation-dallas-tx/liftmaster-la400-swing-gate-opener-installation-dallas-tx-04",
      "widths": [
        400,
        800
      ],
      "width": 1152,
      "height": 1536,
      "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADQAwCdASoQABUAPu1iqU2ppaOiMAgBMB2JYwCw7Bk+FF4/4UBDzQAA/qzseVvj4N0OC5Utms0Tg/22JgccYQhep+gOykIcVJoWRIGJXD9ynlw9M7yuPmjFVL5N++ShhdbBRy7LkLrWvkvjcUcQD7gECp3DA7zFau6lYAAA",
      "caption": "FINAL RESULT"
    },
    {
      "slug": "liftmaster-la400-swing-gate-opener-installation-dallas-tx-05",
      "src": "/images/case-studies/liftmaster-la400-swing-gate-opener-installation-dallas-tx/liftmaster-la400-swing-gate-opener-installation-dallas-tx-05",
      "widths": [
        400,
        800,
        1200
      ],
      "width": 1536,
      "height": 1152,
      "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAwAA4BaJQBOgBe6MtUu3QAA/qnUhsX3v8d99XRWRFoDvnFb2A+WkzLNRzKHTavELGBHQjFz7MMHSjj5CCkEaBV/jo69W9RMBNJeya73OifI2LlTv3SLQAA=",
      "caption": "Watch the completed LiftMaster LA400 installation:"
    }
  ]
}
