// GENERATED by scripts/process-videos.ts — do not edit by hand,
// EXCEPT `title` and `description`, which feed VideoObject schema and must be
// written per video. Set `descriptionWritten: true` once real copy is in.

export type SiteVideo = {
  slug: string
  category: string
  label: string
  src: string
  poster: string
  blurDataURL: string
  durationSeconds: number
  bytes: number
  title: string
  description: string
  descriptionWritten: boolean
}

export const videos: SiteVideo[] = [
  {
    "slug": "all-o-matic-gate-motor-repair-video",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZQC7ADdqYbI3AAA4DQPou74LyGLBtzZC2aO7I0Xwqi4c6yb7a6kAPSm682x31HNGQU8g70MciCd9D2oP1wAAAA=",
    "durationSeconds": 13,
    "bytes": 836388,
    "title": "All-O-Matic Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "all-o-matic-gate-motor-repair-video-2",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJZACxC8AE0N+AAD+wcTLozFkjKzctPrraeSCcgzC++kIYjvEUWcbeDj3yxHKfo9ydYfl50AAAA==",
    "durationSeconds": 17,
    "bytes": 1482063,
    "title": "All-O-Matic Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "automatic-gate-repair-services-video",
    "category": "automatic-gate-repair",
    "label": "Automatic Gate Repair",
    "src": "/videos/automatic-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/automatic-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJYwAAfFAvo8AAP7b611wC/F2VrkvPuHJoSpuOfSghk+mfT+7Z877t6B/IwfiIi++pw+HnWI538iUyRucioAA",
    "durationSeconds": 13,
    "bytes": 1461660,
    "title": "Automatic Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "automatic-gate-repair-services-video-2",
    "category": "automatic-gate-repair",
    "label": "Automatic Gate Repair",
    "src": "/videos/automatic-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/automatic-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJQBOgB7Hs9nd6AAA4jIXMKC3Ov/220Hmy/rH5TGxYhYEDRCyzMyJ75Pg0jZ11E0Yft0LoSUFbuzXAAA=",
    "durationSeconds": 47,
    "bytes": 4602700,
    "title": "Automatic Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "client-testimonial",
    "category": "testimonial",
    "label": "Customer Testimonial",
    "src": "/videos/client-testimonial.mp4",
    "poster": "/images/video-posters/client-testimonial",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQAAjAGDUOQqAD9UyqZCucByYustpRtHuYnKhZZMtQ+rMZb2kKA36FsbMFOqpzWENw4gpWgIJ1IvwAAAA==",
    "durationSeconds": 27,
    "bytes": 2425164,
    "title": "Customer Testimonial — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "commercial-gate-repair-services-video",
    "category": "commercial-gate-repair",
    "label": "Commercial Gate Repair",
    "src": "/videos/commercial-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/commercial-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQCdAD1pQdkgAD+CLqqxrxLifWR9/HWUyFAPeT5YQbOCZUftmn9o2GGl0Zjj0I2MI6A81tVBNQj8QP4AA==",
    "durationSeconds": 10,
    "bytes": 1068012,
    "title": "Commercial Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "commercial-gate-repair-services-video-2",
    "category": "commercial-gate-repair",
    "label": "Commercial Gate Repair",
    "src": "/videos/commercial-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/commercial-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAQCdASoQABAAA4BaJZwAAxPEx1Cv4AD+ifglf30lGbkjWdXQCUQB8+kGgXmMZ2SGJSzMgudycAqMuRiGaW5+QHWGgEJ6IzFK+S4b58GiKy7z1FzFjDp+OrCY3/BfsyLZr1UeoJQ5AAAA",
    "durationSeconds": 37,
    "bytes": 1003534,
    "title": "Commercial Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "eagle-gate-motor-repair-video",
    "category": "eagle",
    "label": "Eagle Gate Operator Repair",
    "src": "/videos/eagle-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/eagle-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZQAAqH7GLVvZoAA4m/3LPbeated/V+vrTUrV8aNIL7Rtov24Q5eatok770tc2dWknWOdTI+I6W/zq8gO41H1drygAAA",
    "durationSeconds": 28,
    "bytes": 2980739,
    "title": "Eagle Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "electric-gate-repair-services-video",
    "category": "electric-gate-repair",
    "label": "Electric Gate Repair",
    "src": "/videos/electric-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/electric-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBOgCFKrx7AAAD+rHAYShwLuwcCTxjNTzoBSCOBNeMFJoouq/Z6l0bquoo3iW4rkhgOySCANBEgqqyQR0zrIAA=",
    "durationSeconds": 16,
    "bytes": 1120637,
    "title": "Electric Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "electric-gate-repair-services-video-2",
    "category": "electric-gate-repair",
    "label": "Electric Gate Repair",
    "src": "/videos/electric-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/electric-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJYwC7AEREXoGTgAA/kkfkSAc6PxQ7Zt+pqxP6A4sS8Uztalv/PeB6S145yDRY6nL9r5AgFOuTLbDXSAAAA==",
    "durationSeconds": 16,
    "bytes": 1584808,
    "title": "Electric Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "elite-gate-motor-repair-video",
    "category": "elite",
    "label": "Elite Gate Operator Repair",
    "src": "/videos/elite-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/elite-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJYwAAfFAvo8AAP7b611wC/F2VrkvPuHJoSpuOfSghk+mfT+7Z877t6B/IwfiIi++pw+HnWI538iUyRucioAA",
    "durationSeconds": 13,
    "bytes": 1460161,
    "title": "Elite Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "elite-gate-motor-repair-video-2",
    "category": "elite",
    "label": "Elite Gate Operator Repair",
    "src": "/videos/elite-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/elite-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJYwCdAD2BS6jv/UAAP7kTeNIuGavUaqGQseYCZPUnQlD3KJFTfo2QB9NAnaxeZ6NWjQV4fdKtwIFDaUsTAafr1oDQAAA",
    "durationSeconds": 12,
    "bytes": 1705192,
    "title": "Elite Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "emergency-gate-repair-services-video",
    "category": "emergency-gate-repair",
    "label": "Emergency Gate Repair",
    "src": "/videos/emergency-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/emergency-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZQC7ADOnliIuwAA/nkJXN/L1NNRRbWV6SmywUwQ4leHp8HQALFx8DU4YNO3mN3/8ZU4JEZ56C/YNtzwCV4AAAA=",
    "durationSeconds": 46,
    "bytes": 4181805,
    "title": "Emergency Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "emergency-gate-repair-services-video-2",
    "category": "emergency-gate-repair",
    "label": "Emergency Gate Repair",
    "src": "/videos/emergency-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/emergency-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJZACdADGd8QIAAD0OcZAjFlPfJQ6KWOao+y5oxlzZt21fB2k67eC2o2Kay5XujrxKV2K3gAAAA==",
    "durationSeconds": 14,
    "bytes": 960426,
    "title": "Emergency Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "faac-gate-motor-repair-video",
    "category": "faac",
    "label": "FAAC Gate Operator Repair",
    "src": "/videos/faac-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/faac-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJZQAAcKszAAA9DnGK/ePG8IdunQglmD8bSOoaQuW9WVLJ9/+wbfrvWuK8NCkwPby4goAAAA=",
    "durationSeconds": 46,
    "bytes": 2738672,
    "title": "FAAC Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "gate-installation-services-video",
    "category": "gate-installation",
    "label": "Gate Installation",
    "src": "/videos/gate-installation-services-video.mp4",
    "poster": "/images/video-posters/gate-installation-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA4BaJQBOgMWblyqJWoAA/qyrka73lYo4zSr8SGcEnTaeaeaubS697NyVTl6wSqR0/ygCporbYfnN5C6/afq4mGLWfdLEJO0iDSgAAA==",
    "durationSeconds": 20,
    "bytes": 1968875,
    "title": "Gate Installation — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "gate-installation-services-video-2",
    "category": "gate-installation",
    "label": "Gate Installation",
    "src": "/videos/gate-installation-services-video-2.mp4",
    "poster": "/images/video-posters/gate-installation-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgCLNAL2lgAD2vlB8/NYve7bP13hhjnLuh12NybuukR0Xpn9bOrqwo/EPyujXnOXkFOXgAA==",
    "durationSeconds": 18,
    "bytes": 1884531,
    "title": "Gate Installation — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "gate-motor-repair-services-video",
    "category": "gate-motor-repair",
    "label": "Gate Motor Repair",
    "src": "/videos/gate-motor-repair-services-video.mp4",
    "poster": "/images/video-posters/gate-motor-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkAA4BaJZwAAwDfApPZIIgA/qN2i9/A1/4pj2Y4ufcGushX5j36BCKN4WyOju+huMzDaIlwAA==",
    "durationSeconds": 15,
    "bytes": 1365550,
    "title": "Gate Motor Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "gate-motor-repair-services-video-2",
    "category": "gate-motor-repair",
    "label": "Gate Motor Repair",
    "src": "/videos/gate-motor-repair-services-video-2.mp4",
    "poster": "/images/video-posters/gate-motor-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJQBdgBowKKhAAPuX+XwgcRfK08c4lkD0wrjjzmxdWP6FxzUjkzeBzPVNJRlp0UTyRdmotqkAAA==",
    "durationSeconds": 21,
    "bytes": 1092201,
    "title": "Gate Motor Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "iron-gate-repair-services-video",
    "category": "iron-gate-repair",
    "label": "Iron Gate Repair",
    "src": "/videos/iron-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/iron-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAgCdASoQAAkAA4BaJYwC7IExgpiuf2uPkiSAAPlpdL4RZnPOCCd2gem7C4MxnR+aEyeP8HLBFyQpWUvJBCDsQYnDrEEoZDyxulCfLnAAAA==",
    "durationSeconds": 20,
    "bytes": 2420048,
    "title": "Iron Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "iron-gate-repair-services-video-2",
    "category": "iron-gate-repair",
    "label": "Iron Gate Repair",
    "src": "/videos/iron-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/iron-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJZQAAxfWokiGHIAA/uuQ2iHWrQpzy90h8OydFO6gMLZVzZgtRXosGo2h2JXvRonmmaEKLunNfg1QAAA=",
    "durationSeconds": 45,
    "bytes": 4433012,
    "title": "Iron Gate Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "liftmaster-gate-motor-repair-video",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdADJs0xwAAD+ox6C6yQHFl/iH1j59IZ+1yml3KWb3/WZZJDEWkp+nTJuXXy6YwTq8qsh6eGNwXAAAA==",
    "durationSeconds": 44,
    "bytes": 4854805,
    "title": "LiftMaster Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "liftmaster-gate-motor-repair-video-2",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCsAEYGmAljbwA/tGa8dENXQb1Kmt+4c+zWQCCkGdPryvDdKeQzY2WjqsmgH2ss2Hy4tg5uohHGS+GDWguoJNkAA==",
    "durationSeconds": 21,
    "bytes": 3224328,
    "title": "LiftMaster Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "ramset-gate-motor-repair-video",
    "category": "ramset",
    "label": "Ramset Gate Operator Repair",
    "src": "/videos/ramset-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/ramset-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkAA4BaJZQCdAEO4g6zS8AA8m0YlaxR7HF+Uq02kWRSpV161+e63NaHsqxckad4pwOV5LN4AA==",
    "durationSeconds": 44,
    "bytes": 3984991,
    "title": "Ramset Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  },
  {
    "slug": "viking-gate-motor-repair-video",
    "category": "viking",
    "label": "Viking Gate Operator Repair",
    "src": "/videos/viking-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/viking-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoQABwAPu1iqk2ppaQiMAgBMB2JQBOgDGBJCBNeX691SoGAAP1dxd4ohgYdyyenWzTfulKVIJESsDVV+TTLBjbn5zbua9SAJ00TEFqQxLsvkk37YTUUgRBfQlethWIDLKDb9NBv8x00bCyKxW36IOUp9hy1DD8WIS9gdOJ4uKLGljR6fN3Qg/487/kabCl1Nj03EpsgkTCM5QWR0MAAAA==",
    "durationSeconds": 8,
    "bytes": 1146363,
    "title": "Viking Gate Operator Repair — Shield Gate Repair, Dallas–Fort Worth",
    "description": "",
    "descriptionWritten": false
  }
]

export function videosFor(category: string): SiteVideo[] {
  return videos.filter((v) => v.category === category)
}
