import { videos, type SiteVideo } from './video-manifest'
import { services, serviceBySlug } from './services'
import { brands, brandBySlug } from './brands'
import { VIDEO_HUB_PATH } from '../lib/video-paths'

/**
 * Per-video watch-page data.
 *
 * ── WHY WATCH PAGES EXIST ───────────────────────────────────────────────────
 * Search Console was reporting the site's videos as not indexed, and two causes
 * were verified against the live site on 13 Sep 2026:
 *
 *  1. No video element in the HTML. `LazyVideo` renders a poster and a button
 *     and only creates the <video> after a click. Googlebot does not click, so
 *     on every page it found a VideoObject describing a video that was not
 *     there. The only <iframe> on those pages was Tag Manager's noscript tag.
 *
 *  2. No watch pages. Google indexes a video only when it is the main content
 *     of its page. All 33 pages carrying VideoObject were text pages of 517 to
 *     2,545 words with video as a supporting section — and 21 of the 30 clips
 *     they described were claimed by two or three pages at once, so Google had
 *     no single page to index any of them under.
 *
 * So each video now has exactly one page at /repair-videos/<slug> where it is
 * the main content, server-rendered as a real <video>, and VideoObject lives
 * only there. Every other page keeps its tile and links to the watch page.
 *
 * ── WHY THIS IS A SEPARATE FILE ─────────────────────────────────────────────
 * content/video-manifest.ts is generated by scripts/process-videos.ts and only
 * `title` and `description` survive a regeneration. Anything else hand-written
 * lives here, keyed by the same slug.
 *
 * ── UPLOAD DATES ────────────────────────────────────────────────────────────
 * `uploadDate` is when the video was first published, which is what schema.org
 * and Google mean by it. Every clip previously carried '2026-08-01' — the day
 * the site was migrated, hardcoded in four files — so every one of them claimed
 * the same publication date regardless of when it went online. The dates below
 * come from two independent sources that agree with each other:
 *
 *  - WordPress footage (25 clips): uploaded to the old WordPress site on this
 *    same domain. The upload dump files them under wordpress-uploads/2026/05/,
 *    and the file timestamps inside it read 14 May 2026 (the testimonial, 15).
 *
 *  - Client footage (8 clips): first published on this site, dated by the git
 *    commit that first added each file to public/videos/. The phone masters in
 *    client-assets/videos/ carry a creation_time of 5 Aug 2026, one day
 *    earlier, which is when they were exported rather than when they went live.
 *
 * A new video without an entry here fails the build — see the guard below —
 * rather than shipping with an invented date.
 *
 * `shortTitle` is used for the <title> tag where the full title, which stays as
 * the H1, would run past Google's ~60-character display budget.
 */

type VideoPageMeta = {
  uploadDate: string
  shortTitle?: string
}

export const VIDEO_PAGES: Record<string, VideoPageMeta> = {
  // ── WordPress footage — first published 14 May 2026 ──────────────────────
  'all-o-matic-gate-motor-repair-video': {
    uploadDate: '2026-05-14',
    shortTitle: 'All-O-Matic Operator Repair — Clutch and Limits',
  },
  'all-o-matic-gate-motor-repair-video-2': { uploadDate: '2026-05-14' },
  'automatic-gate-repair-services-video': { uploadDate: '2026-05-14' },
  'automatic-gate-repair-services-video-2': { uploadDate: '2026-05-14' },
  'commercial-gate-repair-services-video': { uploadDate: '2026-05-14' },
  'commercial-gate-repair-services-video-2': { uploadDate: '2026-05-14' },
  'eagle-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'electric-gate-repair-services-video': { uploadDate: '2026-05-14' },
  'electric-gate-repair-services-video-2': { uploadDate: '2026-05-14' },
  'elite-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'elite-gate-motor-repair-video-2': { uploadDate: '2026-05-14' },
  'emergency-gate-repair-services-video': { uploadDate: '2026-05-14' },
  'emergency-gate-repair-services-video-2': { uploadDate: '2026-05-14' },
  'faac-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'gate-installation-services-video': { uploadDate: '2026-05-14' },
  'gate-installation-services-video-2': {
    uploadDate: '2026-05-14',
    shortTitle: 'Gate Operator Fitting and Commissioning',
  },
  'gate-motor-repair-services-video': { uploadDate: '2026-05-14' },
  'gate-motor-repair-services-video-2': { uploadDate: '2026-05-14' },
  'iron-gate-repair-services-video': { uploadDate: '2026-05-14' },
  'iron-gate-repair-services-video-2': { uploadDate: '2026-05-14' },
  'liftmaster-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'liftmaster-gate-motor-repair-video-2': {
    uploadDate: '2026-05-14',
    shortTitle: 'Inside a LiftMaster — Board and Limit Diagnosis',
  },
  'ramset-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'viking-gate-motor-repair-video': { uploadDate: '2026-05-14' },
  'client-testimonial': { uploadDate: '2026-05-15' },

  // ── Client footage — first committed to public/videos/ ───────────────────
  'all-o-matic-gate-motor-repair-20': { uploadDate: '2026-08-06' },
  'all-o-matic-gate-motor-repair-21': { uploadDate: '2026-08-06' },
  'commercial-gate-repair-services-20': { uploadDate: '2026-08-06' },
  'doorking-gate-motor-repair-20': { uploadDate: '2026-08-06' },
  'liftmaster-gate-motor-repair-20': {
    uploadDate: '2026-08-06',
    shortTitle: 'Corroded LiftMaster Board, Undersized Solar',
  },
  'liftmaster-gate-motor-repair-21': {
    uploadDate: '2026-08-07',
    shortTitle: 'LiftMaster Board Replacement — Battery Going Flat',
  },
  'liftmaster-gate-motor-repair-22': { uploadDate: '2026-08-07' },
  'ramset-gate-motor-repair-20': { uploadDate: '2026-08-06' },
}

// Fail the build rather than publish a watch page with no provenance for its
// date. Runs wherever this module is imported: the watch pages, the hub and the
// sitemap.
const missing = videos.filter((v) => !VIDEO_PAGES[v.slug]).map((v) => v.slug)
if (missing.length > 0) {
  throw new Error(
    `content/video-pages.ts has no entry for ${missing.join(', ')}. ` +
      'Add an uploadDate for each (the date it was first published, with its source) before building.',
  )
}

export const videoBySlug = (slug: string) => videos.find((v) => v.slug === slug)

export function videoPageMeta(slug: string): VideoPageMeta {
  const meta = VIDEO_PAGES[slug]
  if (!meta) throw new Error(`No watch-page entry for video "${slug}".`)
  return meta
}

export const watchTitle = (video: SiteVideo) => VIDEO_PAGES[video.slug]?.shortTitle ?? video.title

/**
 * The page a video's category belongs to. Categories are service or brand
 * slugs by construction (scripts/process-videos.ts), so this resolves them
 * rather than keeping a second hand-written map that could drift.
 */
export function categoryLink(category: string): { label: string; href: string } | null {
  const service = serviceBySlug(category)
  if (service) return { label: service.name, href: `/services/${service.slug}` }
  const brand = brandBySlug(category)
  if (brand) return { label: `${brand.name} gate operators`, href: `/brands/${brand.slug}` }
  if (category === 'testimonial') return { label: 'Customer testimonials', href: '/testimonials' }
  return null
}

/** Same category first, then everything else, so a viewer stays on topic. */
export function relatedVideos(video: SiteVideo, limit = 6): SiteVideo[] {
  const same = videos.filter((v) => v.category === video.category && v.slug !== video.slug)
  const rest = videos.filter((v) => v.category !== video.category)
  return [...same, ...rest].slice(0, limit)
}

export type VideoGroup = { key: string; label: string; href: string; videos: SiteVideo[] }

/**
 * Videos grouped for the hub: services in their site order, then brands by
 * priority, then testimonials. A category that resolves to nothing is still
 * listed under "More repairs" rather than silently dropped from the hub —
 * a watch page nothing links to is an orphan.
 */
export function videoGroups(): VideoGroup[] {
  const order = [
    ...services.map((s) => s.slug),
    ...[...brands].sort((a, b) => a.priority - b.priority).map((b) => b.slug),
    'testimonial',
  ]
  const groups: VideoGroup[] = []
  for (const key of order) {
    const link = categoryLink(key)
    const inGroup = videos.filter((v) => v.category === key)
    if (link && inGroup.length > 0) groups.push({ key, ...link, videos: inGroup })
  }
  const grouped = new Set(groups.flatMap((g) => g.videos.map((v) => v.slug)))
  const orphans = videos.filter((v) => !grouped.has(v.slug))
  if (orphans.length > 0) {
    groups.push({ key: 'other', label: 'More repairs', href: VIDEO_HUB_PATH, videos: orphans })
  }
  return groups
}
