// GENERATED by scripts/process-videos.ts — do not edit by hand,
// EXCEPT `title` and `description`, which feed VideoObject schema and must be
// written per video. Set `descriptionWritten: true` once real copy is in.

export type SiteVideo = {
  slug: string
  category: string
  label: string
  src: string
  poster: string
  blurDataURL: string
  durationSeconds: number
  bytes: number
  title: string
  description: string
  descriptionWritten: boolean
}

export const videos: SiteVideo[] = [
  {
    "slug": "all-o-matic-gate-motor-repair-20",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-20.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-20",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJZACxC8AEyngAP7BxMujMRG30k4/vmgh3dyYeXTe6wsA8XDPZTnbRRTG6kUz2qRLEQSTmezAAA==",
    "durationSeconds": 17,
    "bytes": 1596981,
    "title": "All-O-Matic Slide Operator — Drive and Clutch Service",
    "description": "Service work on an All-O-Matic slide gate operator. These are mechanically straightforward and heavily built, so faults are nearly always a discrete replaceable part — limit cams, clutch, chain or board — rather than a unit that has reached the end of its life.",
    "descriptionWritten": true
  },
  {
    "slug": "all-o-matic-gate-motor-repair-21",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-21.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-21",
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZgCdAYye4BKd7z+CYR5v21oAFVZ0APkzLCreZaMb9Z5wiPMjVBKxLH9D/bv+1QE8kum8FHP0tqI2eBjrbOF9buHtWSieGz+WSdkERX4Z3gQxDSuQ1dwsVUtbxIg7LOZH+cvVgawhd72LBaSmhlLpuzlorLJLpidmrjGeiv/lIuTwJb06V2gIiIetP+VftVquQzhKc6BAAA==",
    "durationSeconds": 27,
    "bytes": 5062301,
    "title": "All-O-Matic Operator — Chain, Sprocket and Limit Check",
    "description": "Checking the chain, sprocket and limit positions on an All-O-Matic operator. Chain stretch is normal and progressive: a stretched chain rides high on the sprocket and wears the teeth, so replacing a chain early is considerably cheaper than replacing a chain, a sprocket and a gearbox later.",
    "descriptionWritten": true
  },
  {
    "slug": "all-o-matic-gate-motor-repair-video",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZQC7ADdqYbI3AAA4DQPou74LyGLBtzZC2aO7I0Xwqi4c6yb7a6kAPSm682x31HNGQU8g70MciCd9D2oP1wAAAA=",
    "durationSeconds": 13,
    "bytes": 836388,
    "title": "All-O-Matic Gate Operator Repair — Clutch and Limit Adjustment",
    "description": "An All-O-Matic operator stalling part-way through travel. The clutch and limit cams are checked and adjusted, and the gate is run through several full cycles to confirm the fix holds under load.",
    "descriptionWritten": true
  },
  {
    "slug": "all-o-matic-gate-motor-repair-video-2",
    "category": "all-o-matic",
    "label": "All-O-Matic Gate Operator Repair",
    "src": "/videos/all-o-matic-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/all-o-matic-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJZACxC8AE0N+AAD+wcTLozFkjKzctPrraeSCcgzC++kIYjvEUWcbeDj3yxHKfo9ydYfl50AAAA==",
    "durationSeconds": 17,
    "bytes": 1482061,
    "title": "All-O-Matic Slide Operator — Chain and Drive Inspection",
    "description": "Inspection of the chain, sprocket and drive assembly on an All-O-Matic slide gate operator. Chain stretch and sprocket wear are the most common mechanical failures on these units and are far cheaper to catch early than to leave running.",
    "descriptionWritten": true
  },
  {
    "slug": "automatic-gate-repair-services-video",
    "category": "automatic-gate-repair",
    "label": "Automatic Gate Repair",
    "src": "/videos/automatic-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/automatic-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJYwAAfFAvo8AAP7b611wC/F2VrkvPuHJoSpuOfSghk+mfT+7Z877t6B/IwfiIi++pw+HnWI538iUyRucioAA",
    "durationSeconds": 13,
    "bytes": 1462289,
    "title": "Automatic Gate Repair — Safety Sensor Fault",
    "description": "A gate that opens but refuses to close is almost always a safety sensor seeing an obstruction that is not there. This shows the photo-eyes being realigned and the gate returned to normal operation.",
    "descriptionWritten": true
  },
  {
    "slug": "automatic-gate-repair-services-video-2",
    "category": "automatic-gate-repair",
    "label": "Automatic Gate Repair",
    "src": "/videos/automatic-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/automatic-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJQBOgB7Hs9nd6AAA4jIXMKC3Ov/220Hmy/rH5TGxYhYEDRCyzMyJ75Pg0jZ11E0Yft0LoSUFbuzXAAA=",
    "durationSeconds": 47,
    "bytes": 4601742,
    "title": "Automatic Gate Repair — Full Repair Walkthrough",
    "description": "A complete automatic gate repair, start to finish: fault identified, cause explained, repair carried out and the gate run through several full cycles to confirm it holds.",
    "descriptionWritten": true
  },
  {
    "slug": "client-testimonial",
    "category": "testimonial",
    "label": "Customer Testimonial",
    "src": "/videos/client-testimonial.mp4",
    "poster": "/images/video-posters/client-testimonial",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQAAjAGDUOQqAD9UyqZCucByYustpRtHuYnKhZZMtQ+rMZb2kKA36FsbMFOqpzWENw4gpWgIJ1IvwAAAA==",
    "durationSeconds": 27,
    "bytes": 2425164,
    "title": "Customer Testimonial — Shield Gate Repair",
    "description": "A Shield Gate Repair customer describing the work carried out on their gate, in their own words. Written reviews are easy to fake, which is why nobody fully believes them any more.",
    "descriptionWritten": true
  },
  {
    "slug": "commercial-gate-repair-services-20",
    "category": "commercial-gate-repair",
    "label": "Commercial Gate Repair",
    "src": "/videos/commercial-gate-repair-services-20.mp4",
    "poster": "/images/video-posters/commercial-gate-repair-services-20",
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JZwCw7B080tpkIigPL3l09lwAAM4yz0YTNULYVU8eNAV5qc/rslxwcE9xn9qQAnfVcfkJQRatcfSSaM7vWRbba0Fo9nDmTTVrh0wvxss36FJWRHaDnxuAXD0dXjl+FEhXtTXw1xQZhSTbAAA=",
    "durationSeconds": 45,
    "bytes": 7940539,
    "title": "Commercial Gate Rebuilt After Vehicle Impact",
    "description": "A commercial entrance gate struck by a vehicle. Impact damage is never only the visible bend — the post was pushed out of plumb and the gate no longer travelled true, so the repair runs structure first, then alignment, then the operator, then the safety devices. Fitting a new operator to a distorted gate simply destroys the new operator too.",
    "descriptionWritten": true
  },
  {
    "slug": "commercial-gate-repair-services-video",
    "category": "commercial-gate-repair",
    "label": "Commercial Gate Repair",
    "src": "/videos/commercial-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/commercial-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQCdAD1pQdkgAD+CLqqxrxLifWR9/HWUyFAPeT5YQbOCZUftmn9o2GGl0Zjj0I2MI6A81tVBNQj8QP4AA==",
    "durationSeconds": 10,
    "bytes": 1068012,
    "title": "Commercial Gate Repair — High-Cycle Entrance",
    "description": "A commercial entrance gate serving hundreds of cycles a day. When the same part fails repeatedly the operator is usually under-specified for the duty cycle, or the gate is making it work far harder than it should.",
    "descriptionWritten": true
  },
  {
    "slug": "commercial-gate-repair-services-video-2",
    "category": "commercial-gate-repair",
    "label": "Commercial Gate Repair",
    "src": "/videos/commercial-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/commercial-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAQCdASoQABAAA4BaJZwAAxPEx1Cv4AD+ifglf30lGbkjWdXQCUQB8+kGgXmMZ2SGJSzMgudycAqMuRiGaW5+QHWGgEJ6IzFK+S4b58GiKy7z1FzFjDp+OrCY3/BfsyLZr1UeoJQ5AAAA",
    "durationSeconds": 37,
    "bytes": 1003534,
    "title": "Commercial Gate Repair — Loop Detector Fault",
    "description": "A commercial gate ignoring approaching vehicles. The fault is in the buried loop and detector rather than the operator — a distinction that gets misdiagnosed constantly and is usually the fastest thing to put right.",
    "descriptionWritten": true
  },
  {
    "slug": "doorking-gate-motor-repair-20",
    "category": "doorking",
    "label": "DoorKing Gate Operator Repair",
    "src": "/videos/doorking-gate-motor-repair-20.mp4",
    "poster": "/images/video-posters/doorking-gate-motor-repair-20",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJZACsAEMw2blC4AA/s9x+0UzeofO+QWE+oZwU21iPOkbrwoOp4+oAxfH7m1rKYXMOcipUqcudaBemH5qg+jaX7ZAAA==",
    "durationSeconds": 23,
    "bytes": 3774493,
    "title": "DoorKing Dual Swing Gate — Gearbox Rebuild",
    "description": "A DoorKing dual swing installation with a failing gearbox. Shows the strip-down, what worn gearing actually looks like against a healthy set, and the rebuild — an operator most companies would have quoted for outright replacement.",
    "descriptionWritten": true
  },
  {
    "slug": "eagle-gate-motor-repair-video",
    "category": "eagle",
    "label": "Eagle Gate Operator Repair",
    "src": "/videos/eagle-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/eagle-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAkAA4BaJZQAAqH7GLVvZoAA4m/3LPbeated/V+vrTUrV8aNIL7Rtov24Q5eatok770tc2dWknWOdTI+I6W/zq8gO41H1drygAAA",
    "durationSeconds": 28,
    "bytes": 2982432,
    "title": "Eagle Gate Operator Repair — Fault Diagnosis and Fix",
    "description": "An Eagle gate operator diagnosed and repaired on site. Eagle units are reliable enough that when they do fail it is usually a single serviceable component with a long life ahead of it once replaced.",
    "descriptionWritten": true
  },
  {
    "slug": "electric-gate-repair-services-video",
    "category": "electric-gate-repair",
    "label": "Electric Gate Repair",
    "src": "/videos/electric-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/electric-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBOgCFKrx7AAAD+rHAYShwLuwcCTxjNTzoBSCOBNeMFJoouq/Z6l0bquoo3iW4rkhgOySCANBEgqqyQR0zrIAA=",
    "durationSeconds": 16,
    "bytes": 1120637,
    "title": "Electric Gate Repair — Tracing an Electrical Fault",
    "description": "Tracing an intermittent fault on an electric gate: supply voltage checked at source and at the operator, terminals inspected for corrosion, and accessories isolated to find a short — rather than replacing parts one at a time.",
    "descriptionWritten": true
  },
  {
    "slug": "electric-gate-repair-services-video-2",
    "category": "electric-gate-repair",
    "label": "Electric Gate Repair",
    "src": "/videos/electric-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/electric-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJYwC7AEREXoGTgAA/kkfkSAc6PxQ7Zt+pqxP6A4sS8Uztalv/PeB6S145yDRY6nL9r5AgFOuTLbDXSAAAA==",
    "durationSeconds": 16,
    "bytes": 1584808,
    "title": "Electric Gate Repair — Transformer and Power Supply Check",
    "description": "Testing the transformer and power supply on an electric gate that had stopped responding entirely. Shows why the power path is checked before the control board is suspected.",
    "descriptionWritten": true
  },
  {
    "slug": "elite-gate-motor-repair-video",
    "category": "elite",
    "label": "Elite Gate Operator Repair",
    "src": "/videos/elite-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/elite-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJYwAAfFAvo8AAP7b611wC/F2VrkvPuHJoSpuOfSghk+mfT+7Z877t6B/IwfiIi++pw+HnWI538iUyRucioAA",
    "durationSeconds": 13,
    "bytes": 1460370,
    "title": "Elite Gate Operator Repair — Control Board Replacement",
    "description": "Replacing a failed control board in an Elite gate operator. The old board is tested to confirm the diagnosis before anything is replaced, so the customer is not paying for a guess.",
    "descriptionWritten": true
  },
  {
    "slug": "elite-gate-motor-repair-video-2",
    "category": "elite",
    "label": "Elite Gate Operator Repair",
    "src": "/videos/elite-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/elite-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJYwCdAD2BS6jv/UAAP7kTeNIuGavUaqGQseYCZPUnQlD3KJFTfo2QB9NAnaxeZ6NWjQV4fdKtwIFDaUsTAafr1oDQAAA",
    "durationSeconds": 12,
    "bytes": 1704177,
    "title": "Elite Slide Gate Operator — Drive and Travel Check",
    "description": "An Elite slide operator run through full travel after service, checking limit positions, safety devices and chain tension. This is the final step on every repair before the technician leaves.",
    "descriptionWritten": true
  },
  {
    "slug": "emergency-gate-repair-services-video",
    "category": "emergency-gate-repair",
    "label": "Emergency Gate Repair",
    "src": "/videos/emergency-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/emergency-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJZQC7ADOnliIuwAA/nkJXN/L1NNRRbWV6SmywUwQ4leHp8HQALFx8DU4YNO3mN3/8ZU4JEZ56C/YNtzwCV4AAAA=",
    "durationSeconds": 46,
    "bytes": 4181568,
    "title": "Emergency Gate Repair — Same-Day Call-Out",
    "description": "An emergency call-out on a gate stuck open. A gate stuck open is a security problem, not an inconvenience, and is treated as urgent regardless of the underlying cause.",
    "descriptionWritten": true
  },
  {
    "slug": "emergency-gate-repair-services-video-2",
    "category": "emergency-gate-repair",
    "label": "Emergency Gate Repair",
    "src": "/videos/emergency-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/emergency-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJZACdADGd8QIAAD0OcZAjFlPfJQ6KWOao+y5oxlzZt21fB2k67eC2o2Kay5XujrxKV2K3gAAAA==",
    "durationSeconds": 14,
    "bytes": 958597,
    "title": "Emergency Gate Repair — Manual Release and Temporary Secure",
    "description": "How a gate is released to manual operation so a property can be used before the repair is complete, and how a gate is left in a secure state when a part has to be ordered.",
    "descriptionWritten": true
  },
  {
    "slug": "faac-gate-motor-repair-video",
    "category": "faac",
    "label": "FAAC Gate Operator Repair",
    "src": "/videos/faac-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/faac-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAkAA4BaJZQAAcKszAAA9DnGK/ePG8IdunQglmD8bSOoaQuW9WVLJ9/+wbfrvWuK8NCkwPby4goAAAA=",
    "durationSeconds": 46,
    "bytes": 2739227,
    "title": "FAAC Gate Operator Repair — Hydraulic Service",
    "description": "FAAC builds hydraulic gate operators, which need different diagnostics and different parts to a chain drive. This shows the repair being carried out: pressure checked, seals addressed and the operator returned to normal travel speed.",
    "descriptionWritten": true
  },
  {
    "slug": "gate-installation-services-video",
    "category": "gate-installation",
    "label": "Gate Installation",
    "src": "/videos/gate-installation-services-video.mp4",
    "poster": "/images/video-posters/gate-installation-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA4BaJQBOgMWblyqJWoAA/qyrka73lYo4zSr8SGcEnTaeaeaubS697NyVTl6wSqR0/ygCporbYfnN5C6/afq4mGLWfdLEJO0iDSgAAA==",
    "durationSeconds": 20,
    "bytes": 1966074,
    "title": "Automatic Gate Installation — Site Preparation and Footings",
    "description": "The part of a gate installation nobody sees and everything depends on: footings set to depth, conduit run properly and power brought to the gate correctly the first time. Skipping this is how a gate becomes an annual repair call.",
    "descriptionWritten": true
  },
  {
    "slug": "gate-installation-services-video-2",
    "category": "gate-installation",
    "label": "Gate Installation",
    "src": "/videos/gate-installation-services-video-2.mp4",
    "poster": "/images/video-posters/gate-installation-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkAA4BaJQBOgCLNAL2lgAD2vlB8/NYve7bP13hhjnLuh12NybuukR0Xpn9bOrqwo/EPyujXnOXkFOXgAA==",
    "durationSeconds": 18,
    "bytes": 1883990,
    "title": "Automatic Gate Installation — Operator Fitting and Commissioning",
    "description": "Fitting and commissioning the operator on a new gate installation: alignment set, limits programmed, safety devices installed to standard and the whole system handed over working.",
    "descriptionWritten": true
  },
  {
    "slug": "gate-motor-repair-services-video",
    "category": "gate-motor-repair",
    "label": "Gate Motor Repair",
    "src": "/videos/gate-motor-repair-services-video.mp4",
    "poster": "/images/video-posters/gate-motor-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkAA4BaJZwAAwDfApPZIIgA/qN2i9/A1/4pj2Y4ufcGushX5j36BCKN4WyOju+huMzDaIlwAA==",
    "durationSeconds": 15,
    "bytes": 1365550,
    "title": "Gate Motor Repair — How We Diagnose a Dead Operator",
    "description": "The diagnostic sequence for a gate that will not move: gate released and pushed by hand to rule out a mechanical bind, then power at the board, capacitor under load, limit switch travel and safety devices — in that order.",
    "descriptionWritten": true
  },
  {
    "slug": "gate-motor-repair-services-video-2",
    "category": "gate-motor-repair",
    "label": "Gate Motor Repair",
    "src": "/videos/gate-motor-repair-services-video-2.mp4",
    "poster": "/images/video-posters/gate-motor-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJQBdgBowKKhAAPuX+XwgcRfK08c4lkD0wrjjzmxdWP6FxzUjkzeBzPVNJRlp0UTyRdmotqkAAA==",
    "durationSeconds": 21,
    "bytes": 1092201,
    "title": "Gate Motor Repair — Capacitor Test and Replacement",
    "description": "A gate motor that hums but will not move is far more often a failed capacitor than a dead motor. This shows the capacitor being tested under load and replaced, one of the least expensive repairs on a gate.",
    "descriptionWritten": true
  },
  {
    "slug": "iron-gate-repair-services-video",
    "category": "iron-gate-repair",
    "label": "Iron Gate Repair",
    "src": "/videos/iron-gate-repair-services-video.mp4",
    "poster": "/images/video-posters/iron-gate-repair-services-video",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAgCdASoQAAkAA4BaJYwC7IExgpiuf2uPkiSAAPlpdL4RZnPOCCd2gem7C4MxnR+aEyeP8HLBFyQpWUvJBCDsQYnDrEEoZDyxulCfLnAAAA==",
    "durationSeconds": 20,
    "bytes": 2420048,
    "title": "Iron Gate Repair — Weld Repair on a Cracked Frame",
    "description": "A cracked weld at an iron gate frame joint cut out, re-welded, ground back and refinished so the repair is not visible. Custom ironwork is almost always worth repairing rather than replacing.",
    "descriptionWritten": true
  },
  {
    "slug": "iron-gate-repair-services-video-2",
    "category": "iron-gate-repair",
    "label": "Iron Gate Repair",
    "src": "/videos/iron-gate-repair-services-video-2.mp4",
    "poster": "/images/video-posters/iron-gate-repair-services-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJZQAAxfWokiGHIAA/uuQ2iHWrQpzy90h8OydFO6gMLZVzZgtRXosGo2h2JXvRonmmaEKLunNfg1QAAA=",
    "durationSeconds": 45,
    "bytes": 4429905,
    "title": "Iron Gate Repair — Fixing a Sagging Gate",
    "description": "A sagging iron gate dragging on the driveway. The hinges and the post are assessed together with the gate, because straightening the leaf without addressing the post means it will drag again within a season.",
    "descriptionWritten": true
  },
  {
    "slug": "liftmaster-gate-motor-repair-20",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-20.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-20",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJQBOgCPTYEMLYAD+5E1DDxPz9cJ7HREMsyK9yRrqnRYgwQl74se86AMsNf1yk6UjTlx4QCpa9DUFkowYX64AAAA=",
    "durationSeconds": 14,
    "bytes": 2559618,
    "title": "Moisture-Corroded LiftMaster Board and an Undersized Solar Array",
    "description": "A solar LiftMaster on a rural double farm gate that had been getting slower for months before it stopped. Water ingress had corroded the control board, and testing the power side showed the solar array had never been sized for the gate — so the batteries had been running permanently undercharged, stressing the electronics that failed. Board replaced, enclosure resealed, array resized to the actual load.",
    "descriptionWritten": true
  },
  {
    "slug": "liftmaster-gate-motor-repair-21",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-21.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-21",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBdgB6J+wZLtgAA++xUwz0j3NiYWKBazUAYBA1+vQ4wu25BBLmyTTnh0EO76wsiTjNEZ72Z2OFZYMbGAA==",
    "durationSeconds": 19,
    "bytes": 1967935,
    "title": "LiftMaster Board Replacement — When the Battery Keeps Going Flat",
    "description": "A solar-powered LiftMaster whose battery kept dying, including a brand-new replacement. The battery load-tested fine and the panel was producing correctly — the charging circuit on the control board had failed, so every cycle drew the battery down with nothing putting charge back. Board replaced, charge current verified at the battery before closing up, and backed with a 3-year warranty.",
    "descriptionWritten": true
  },
  {
    "slug": "liftmaster-gate-motor-repair-22",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-22.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-22",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAkAA4BaJZQAAuR1xZ+4AAD++E8EMipdKHb0nVZfy2deZFn1bXqaPAS4AA==",
    "durationSeconds": 18,
    "bytes": 1040239,
    "title": "LiftMaster LA400 to LA500 — Upgrading Only the Arm",
    "description": "A heavy arched iron swing gate whose LA400 arm was not rated to carry it. The gate swung freely by hand, so the fault was specification rather than wear. The LA500 shares a control platform with the LA400, so the heavy-duty arm went on and the existing control board, box and wiring stayed exactly where they were.",
    "descriptionWritten": true
  },
  {
    "slug": "liftmaster-gate-motor-repair-video",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJYwCdADJs0xwAAD+ox6C6yQHFl/iH1j59IZ+1yml3KWb3/WZZJDEWkp+nTJuXXy6YwTq8qsh6eGNwXAAAA==",
    "durationSeconds": 44,
    "bytes": 4853785,
    "title": "LiftMaster Gate Operator Repair — Full Service Call",
    "description": "A complete LiftMaster gate operator repair from diagnosis to test cycle. The technician isolates the fault at the control board, replaces the failed component and runs the gate through full travel before leaving. Most LiftMaster faults are a board, a capacitor or a limit switch — not the whole operator.",
    "descriptionWritten": true
  },
  {
    "slug": "liftmaster-gate-motor-repair-video-2",
    "category": "liftmaster",
    "label": "LiftMaster Gate Operator Repair",
    "src": "/videos/liftmaster-gate-motor-repair-video-2.mp4",
    "poster": "/images/video-posters/liftmaster-gate-motor-repair-video-2",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAkAA4BaJYwCsAEYGmAljbwA/tGa8dENXQb1Kmt+4c+zWQCCkGdPryvDdKeQzY2WjqsmgH2ss2Hy4tg5uohHGS+GDWguoJNkAA==",
    "durationSeconds": 21,
    "bytes": 3228481,
    "title": "Inside a LiftMaster Operator — Board and Limit Switch Diagnosis",
    "description": "Close-up of a LiftMaster operator opened on site. Shows how the control board, limit switches and drive chain are checked in sequence, and why the gate itself is moved by hand first to separate a mechanical bind from an electrical fault.",
    "descriptionWritten": true
  },
  {
    "slug": "ramset-gate-motor-repair-20",
    "category": "ramset",
    "label": "Ramset Gate Operator Repair",
    "src": "/videos/ramset-gate-motor-repair-20.mp4",
    "poster": "/images/video-posters/ramset-gate-motor-repair-20",
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAkAA4BaJQBWABjzIfPyHAD+6Zbsy0wqmHBM9LiNncWLoP06OojZgUQsbdaL4PrDYlX/WIxXGI9SlXwpIlne9AbikW7cHZoQwx4nAAA=",
    "durationSeconds": 18,
    "bytes": 2139617,
    "title": "Ramset Slide Gate — Worn Rollers Destroying the Drive",
    "description": "A Ramset slide operator straining on every cycle. The fault was not in the operator: the rollers had flat-spotted and the track had loaded with grit, so the gate had become far harder to move than the unit was ever specified for. Rollers replaced and track cleared, with the operator left in service.",
    "descriptionWritten": true
  },
  {
    "slug": "ramset-gate-motor-repair-video",
    "category": "ramset",
    "label": "Ramset Gate Operator Repair",
    "src": "/videos/ramset-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/ramset-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkAA4BaJZQCdAEO4g6zS8AA8m0YlaxR7HF+Uq02kWRSpV161+e63NaHsqxckad4pwOV5LN4AA==",
    "durationSeconds": 44,
    "bytes": 3984991,
    "title": "Ramset Gate Operator Repair — High-Cycle Commercial Unit",
    "description": "A Ramset operator on a high-cycle commercial entrance. Shows why parts that last a decade on a residential driveway wear out in months on a gate running hundreds of cycles a day, and what to check when the same component keeps failing.",
    "descriptionWritten": true
  },
  {
    "slug": "viking-gate-motor-repair-video",
    "category": "viking",
    "label": "Viking Gate Operator Repair",
    "src": "/videos/viking-gate-motor-repair-video.mp4",
    "poster": "/images/video-posters/viking-gate-motor-repair-video",
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwAwCdASoQABwAPu1iqk2ppaQiMAgBMB2JQBOgDGBJCBNeX691SoGAAP1dxd4ohgYdyyenWzTfulKVIJESsDVV+TTLBjbn5zbua9SAJ00TEFqQxLsvkk37YTUUgRBfQlethWIDLKDb9NBv8x00bCyKxW36IOUp9hy1DD8WIS9gdOJ4uKLGljR6fN3Qg/487/kabCl1Nj03EpsgkTCM5QWR0MAAAA==",
    "durationSeconds": 8,
    "bytes": 1146363,
    "title": "Viking Gate Operator Repair — DC Power and Battery Diagnosis",
    "description": "Viking operators typically run on DC with battery and solar or trickle charging, so a gate that has become slow or unreliable is often a power problem rather than an operator fault. This shows the charging system being load-tested before anything mechanical is condemned.",
    "descriptionWritten": true
  }
]

export function videosFor(category: string): SiteVideo[] {
  return videos.filter((v) => v.category === category)
}
