/**
 * Geocodes the service-area city list into content/city-coordinates.ts.
 *
 * Coordinates are LOOKED UP, never guessed. Plausible-looking latitude and
 * longitude for a real town is the worst kind of wrong data — it renders fine,
 * it is never obviously broken, and it silently puts a pin in the wrong place
 * on a map a customer is using to decide whether we cover them.
 *
 * Source: OpenStreetMap Nominatim. Free, no API key, and the same data behind
 * the basemap tiles, so pins and tiles agree with each other.
 *
 * Nominatim's usage policy caps this at 1 request/second and requires a real
 * User-Agent. Both are honoured below. That makes a cold run ~190 seconds, so
 * results are cached: re-running only fetches cities that are missing or
 * previously failed. Do not remove the throttle.
 *
 *   npm run geocode
 *   npm run geocode -- --force        # re-fetch everything
 */

import { promises as fs } from 'node:fs'
import path from 'node:path'
import { cities } from '../content/cities'

const OUT = path.join(process.cwd(), 'content', 'city-coordinates.ts')
const ENDPOINT = 'https://nominatim.openstreetmap.org/search'
const USER_AGENT = 'ShieldGateRepairSiteBuild/1.0 (+https://shieldgaterepair.com; office@shieldgaterepair.com)'
const DELAY_MS = 1100

type Coords = { lat: number; lng: number }

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function readExisting(): Promise<Record<string, Coords>> {
  try {
    const mod = await import('../content/city-coordinates')
    return { ...(mod.CITY_COORDINATES as Record<string, Coords>) }
  } catch {
    return {}
  }
}

async function geocode(name: string, county: string): Promise<Coords | null> {
  // County is included so "Paradise" and "Point" resolve to the Texas towns
  // rather than the many other places sharing those names.
  const params = new URLSearchParams({
    format: 'jsonv2',
    limit: '1',
    country: 'United States',
    state: 'Texas',
    county,
    city: name,
  })

  const res = await fetch(`${ENDPOINT}?${params}`, { headers: { 'User-Agent': USER_AGENT } })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const json = (await res.json()) as { lat: string; lon: string }[]
  if (!json.length) return null

  return { lat: Number(Number(json[0].lat).toFixed(5)), lng: Number(Number(json[0].lon).toFixed(5)) }
}

/** Second attempt without the county filter — some small towns are not tagged with one. */
async function geocodeLoose(name: string): Promise<Coords | null> {
  const params = new URLSearchParams({
    format: 'jsonv2',
    limit: '1',
    q: `${name}, Texas, United States`,
  })
  const res = await fetch(`${ENDPOINT}?${params}`, { headers: { 'User-Agent': USER_AGENT } })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const json = (await res.json()) as { lat: string; lon: string }[]
  if (!json.length) return null
  return { lat: Number(Number(json[0].lat).toFixed(5)), lng: Number(Number(json[0].lon).toFixed(5)) }
}

async function main() {
  const force = process.argv.includes('--force')
  const known = force ? {} : await readExisting()

  const todo = cities.filter((c) => !known[c.slug])
  console.log(`${cities.length} cities, ${Object.keys(known).length} already cached, ${todo.length} to fetch`)
  if (todo.length > 0) console.log(`~${Math.ceil((todo.length * DELAY_MS) / 1000)}s at the required 1 req/sec\n`)

  const failed: string[] = []

  for (const [i, city] of todo.entries()) {
    try {
      let coords = await geocode(city.name, city.county)
      if (!coords) {
        await sleep(DELAY_MS)
        coords = await geocodeLoose(city.name)
      }
      if (coords) {
        known[city.slug] = coords
        console.log(`  [${i + 1}/${todo.length}] ${city.name} -> ${coords.lat}, ${coords.lng}`)
      } else {
        failed.push(city.name)
        console.log(`  [${i + 1}/${todo.length}] ${city.name} -> NOT FOUND`)
      }
    } catch (err) {
      failed.push(city.name)
      console.log(`  [${i + 1}/${todo.length}] ${city.name} -> ERROR ${(err as Error).message}`)
    }
    await sleep(DELAY_MS)
  }

  const ordered = Object.keys(known).sort()
  const body = `/**
 * GENERATED by scripts/geocode-cities.ts — do not edit by hand.
 *
 * Latitude/longitude for every service-area city, resolved from OpenStreetMap
 * Nominatim. Committed so the site builds without network access and so we are
 * not re-querying a donated public service on every deploy.
 *
 * Missing a city? Run \`npm run geocode\` — it only fetches what is absent.
 */

export type CityCoords = { lat: number; lng: number }

export const CITY_COORDINATES: Record<string, CityCoords> = {
${ordered.map((slug) => `  '${slug}': { lat: ${known[slug].lat}, lng: ${known[slug].lng} },`).join('\n')}
}
`
  await fs.writeFile(OUT, body, 'utf8')

  console.log(`\n${ordered.length}/${cities.length} cities geocoded -> ${path.relative(process.cwd(), OUT)}`)
  if (failed.length) {
    console.log(`\n⚠️  ${failed.length} not resolved. They are omitted from the map rather than guessed:`)
    for (const f of failed) console.log(`   ${f}`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
