/**
 * Turns the extracted case-study photographs into responsive web images.
 *
 * ── WHY A SEPARATE PIPELINE FROM process-assets.ts ──────────────────────────
 * That script exists to sort a WordPress dump into shared, interchangeable
 * pools: a service page asks for "three liftmaster photos" and gets whichever
 * three. It assigns indices per category, which is exactly right for stock
 * library photography and exactly wrong here.
 *
 * These are ordered sets belonging to one job each, captioned individually,
 * grouped before/during/after by the client. Photo 3 of the Viking
 * refurbishment is not interchangeable with photo 3 of anything else. Forcing
 * them through the pool model would either scramble the order or require 18
 * new categories, and either way it would put the existing 251 pages' imagery
 * at risk for no benefit.
 *
 * So: same encoder settings, same widths, separate output tree and separate
 * manifest.
 *
 *   npx tsx scripts/process-case-study-photos.ts
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const SOURCE = path.join(process.cwd(), 'client-assets', 'case-studies')
const OUT_DIR = path.join(process.cwd(), 'public', 'images', 'case-studies')
const MANIFEST = path.join(process.cwd(), 'content', 'case-study-media.ts')

/**
 * No 2000px tier.
 *
 * Case-study photographs are never a full-bleed hero — they render in a gallery
 * grid at roughly half the viewport at most. Encoding a 2000px AVIF of 111
 * images to serve a size nothing requests would add minutes to every build and
 * megabytes to the repo for no delivered pixel.
 */
const WIDTHS = [400, 800, 1200, 1600] as const

/** Matches process-assets.ts so the two libraries look identical on the page. */
const AVIF_QUALITY = 50
const WEBP_QUALITY = 78

type Extracted = { slug: string; docx: string; photos: { file: string; caption: string }[] }

type Entry = {
  slug: string
  src: string
  widths: number[]
  width: number
  height: number
  blurDataURL: string
  caption: string
}

async function main() {
  const raw = await fs.readFile(path.join(SOURCE, 'extracted.json'), 'utf8')
  const studies = JSON.parse(raw) as Extracted[]

  await fs.mkdir(OUT_DIR, { recursive: true })
  const manifest: Record<string, Entry[]> = {}

  let done = 0
  let skipped = 0

  for (const study of studies) {
    const outDir = path.join(OUT_DIR, study.slug)
    await fs.mkdir(outDir, { recursive: true })
    const entries: Entry[] = []

    for (const [i, photo] of study.photos.entries()) {
      const source = path.join(SOURCE, study.slug, photo.file)
      const n = String(i + 1).padStart(2, '0')
      const slug = `${study.slug}-${n}`
      const probe = path.join(outDir, `${slug}-800.avif`)

      let meta: sharp.Metadata
      try {
        meta = await sharp(source).metadata()
      } catch {
        console.warn(`  ! unreadable: ${source}`)
        continue
      }

      const widths = WIDTHS.filter((w) => w <= (meta.width ?? 0))
      if (widths.length === 0) widths.push(WIDTHS[0])

      // Skip work already done, so a re-run after adding one study is quick.
      let exists = false
      try {
        await fs.access(probe)
        exists = true
      } catch {
        exists = false
      }

      if (!exists) {
        const pipeline = sharp(source).rotate()
        await Promise.all(
          widths.flatMap((w) => {
            const resized = pipeline.clone().resize(w)
            return [
              resized.clone().avif({ quality: AVIF_QUALITY, effort: 4 }).toFile(path.join(outDir, `${slug}-${w}.avif`)),
              resized.clone().webp({ quality: WEBP_QUALITY }).toFile(path.join(outDir, `${slug}-${w}.webp`)),
            ]
          }),
        )
        done++
      } else {
        skipped++
      }

      const blurBuf = await sharp(source).rotate().resize(16).webp({ quality: 40 }).toBuffer()

      entries.push({
        slug,
        src: `/images/case-studies/${study.slug}/${slug}`,
        widths: [...widths],
        width: meta.width ?? 0,
        height: meta.height ?? 0,
        blurDataURL: `data:image/webp;base64,${blurBuf.toString('base64')}`,
        caption: photo.caption,
      })
    }

    manifest[study.slug] = entries
    console.log(`${study.slug.padEnd(62)} ${entries.length} photos`)
  }

  const header = `// GENERATED by scripts/process-case-study-photos.ts — do not edit by hand,
// EXCEPT the \`caption\` fields, which are the client's own words from the
// source documents and may be improved by a human.
//
// These are real job photographs supplied by the client with the case-study
// write-ups. Unlike content/media-manifest.ts, these sets are ORDERED and
// belong to one job each — the client grouped them before/during/after and
// captioned them individually, so the order here is meaningful and must not be
// sorted or shuffled by anything that renders them.

export type CaseStudyPhoto = {
  slug: string
  src: string
  widths: number[]
  width: number
  height: number
  blurDataURL: string
  caption: string
}

export const caseStudyPhotos: Record<string, CaseStudyPhoto[]> = `

  await fs.writeFile(MANIFEST, header + JSON.stringify(manifest, null, 2) + '\n')

  const total = Object.values(manifest).reduce((n, v) => n + v.length, 0)
  console.log(`\n${Object.keys(manifest).length} case studies, ${total} photos`)
  console.log(`encoded ${done}, skipped ${skipped} already present`)
  console.log(`manifest → content/case-study-media.ts`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
